INSERT IGNORE INTO obras_sociales (nombre) VALUES
('A.A.M.M - Asoc. Argentina Mut.del Motociclista Plan unico'),
('A.A.M.M - Asoc. Argentina Mut.del Motociclista Plan unico'),
('A.C.R S.A Plan Único'),
('A.M.B.A.R. (Asociación Mutual Bancarios Roca) Plan Bronce'),
('A.M.B.A.R. (Asociación Mutual Bancarios Roca) Plan Oro'),
('A.M.B.A.R. (Asociación Mutual Bancarios Roca) Plan Plata'),
('A.M.P.J.B.O.N. - Asoc. Mut. Personal Jerárquico de Bancos Oficiales Plan unico'),
('A.T.E JACHAL Plan Unico'),
('A.T.E SAN JUAN Plan Unico'),
('A.Y.E.E. Plan único'),
('AATRA (Telegrafistas) Plan Medico Obligatorio'),
('Aca Hercules Bienestar Salud'),
('Aca Hercules Familia Protegida'),
('Aca Hercules Salud Total'),
('Aca Salud Aca Salud'),
('Aca Salud Integral'),
('Aca Salud Plan Médico Obligatorio'),
('Aca Salud Plan Único'),
('Aca Salud Selecta'),
('Aca Salud Superior'),
('Accord salud 0002'),
('Accord salud 0003'),
('Accord salud 0202'),
('Accord salud Accord 1.5'),
('Accord salud Accord 101'),
('Accord salud Accord 102'),
('Accord salud Accord 110'),
('Accord salud Accord 150'),
('Accord salud Accord 2.2'),
('Accord salud Accord 210'),
('Accord salud Accord 211'),
('Accord salud Accord 220'),
('Accord salud Accord 3.2'),
('Accord salud Accord 310'),
('Accord salud Accord 320'),
('Accord salud Accord 4.2'),
('Accord salud Azul'),
('Accord salud Plan AC211'),
('Accord salud Plan Dorado'),
('Accord salud Plan Platino'),
('Accord salud Plan Verde'),
('ACES Plan úncio'),
('ACES Plan único'),
('ACES Plan único'),
('ACES Plan único'),
('ACES Plan único'),
('ACES Plan único'),
('ACES Plan único'),
('ACLISASA Red de Prestadores'),
('ACTIM (Campesinos Tabacaleros Independientes) Plan Médico Obligatorio'),
('Activa Salud OSCONARA'),
('Activa Salud OSPADEP'),
('Activa Salud OSSEG INTEGRAL ADHERENTES'),
('Activa Salud Plan AS-150 OSEN'),
('Activa Salud Plan AS-150 OSPADEP'),
('Activa Salud Plan AS-200 OSEN'),
('Activa Salud Plan AS-200 OSPADEP'),
('Activa Salud Plan AS-25 M OSFATLYF'),
('Activa Salud Plan AS-25 OSEN'),
('Activa Salud Plan AS-300 OSPADEP'),
('Activa Salud Plan AS-50 OSEN'),
('Activa Salud Plan AS-50 OSPADEP'),
('Activa Salud Plan AS-500 E / AS-500 E SERVESALUD'),
('Activa Salud Plan AS-500 SERVESALUD'),
('Activa Salud Plan AS-610 OSPTA'),
('Activa Salud Plan AS-700 E / AS-700 E SERVESALUD'),
('Activa Salud Plan AS-700 OSEN'),
('Activa Salud Plan AS-700 SERVESALUD'),
('Activa Salud Plan AS-710 OSPTA'),
('Activa Salud Plan AS-800-E / AS-800 E SERVESALUD'),
('Activa Salud Plan AS-800 OSEN'),
('Activa Salud Plan AS-800 OSFATLYF'),
('Activa Salud Plan AS-800 SERVESALUD'),
('Activa Salud PLAN AS-910 CAMPSIC'),
('Activa Salud PLAN AS-910 E CAMPSIC'),
('Activa Salud PLAN AS-980 CAMPSIC'),
('Activa Salud PLAN AS-980 E CAMPSIC'),
('Activa Salud Plan Medico Obligatorio'),
('adicional lectora credencia Plan unico'),
('Admed srl Plan único'),
('ADOS Plan Único'),
('ADS Plan único'),
('Aerocomerciales Plan Único'),
('AESP Plan único'),
('Agua y energía Plan Único'),
('AJB (Asociacion Judicial Bonaerense) Plan Médico Obligatorio'),
('Alianza Medica Clásico 70'),
('Alianza Medica Global 100'),
('Alianza Medica Plan Joven'),
('Alianza Medica Senior'),
('Alianza Medica Superior 85'),
('Alianza Mediterranea de Salud Plan Medico Obligatorio'),
('All Medicine Plan Minero'),
('All Medicine Plan Oro'),
('All Medicine Plan Plata'),
('All Medicine Plan Vida'),
('ALL SALUD Plan Unico'),
('Alta Salud Plan Medico Obligatorio'),
('AMBB Plan único'),
('Ambulancias Evangelistas Argentinas Plan Único'),
('AMC SALUD S.A. AMC 100'),
('AMC SALUD S.A. AMC 70'),
('AMC SALUD S.A. AMC 70 T'),
('AMC SALUD S.A. AMC 85'),
('AMCI (Asociación Mutual de Control Integral) Plan Medico Obligatorio'),
('AMEBPBA - ASOC.MUTUAL EMP.BANCO.PROV.DE BS.AS. Plan único'),
('AMEP Plan Medico Obligatorio'),
('AMEPBA Plan único'),
('América Servicios S.A Plan Médico Obligatorio'),
('AMFA Plan Único'),
('Amffa Plan Único'),
('Amia Plan Único'),
('AMICOS Plan Medico Obligatorio'),
('AMISA Plan Unico'),
('AMMA SALUD Plan Clásico'),
('AMMA SALUD Plan Joven'),
('AMMA SALUD Plan Superior'),
('AMMECO Plan B'),
('AMMECO Plan Dorado'),
('AMMECO Plan Familia'),
('AMMECO Plan Joven'),
('AMMFA Plan Único'),
('Amor y Paz Plan Médico Obligatorio'),
('AMP (As. Mutual Policial) Plan Médico Obligatorio'),
('AMPARAS 410'),
('AMPARAS A01'),
('AMPARAS A01 MAS'),
('AMPARAS Plan Pulso'),
('AMPES Salud Plan platino'),
('AMPES Salud Plan único'),
('AMPFA (MAUT. FARMACIA) Plan Unico'),
('AMPS Plan 1000'),
('AMPS Plan 2000'),
('AMPS Plan 3000'),
('AMPS Plan 4000'),
('AMPS Plan 500'),
('AMPS Plan C'),
('AMPS Plan Jubilados'),
('AMR SALUD 1000/01'),
('AMR SALUD 2000'),
('AMR SALUD 2000/01'),
('AMR SALUD Dorado'),
('AMR SALUD Especial'),
('AMR SALUD H+E'),
('AMR SALUD Oro'),
('AMR SALUD Plan Integral'),
('AMR SALUD Plan Novo'),
('AMR SALUD Plan RED'),
('AMR SALUD Sol'),
('AMS CIEN'),
('AMS JADE'),
('AMSAR Plan Unico'),
('AMSESBA Plan Medico Obligatorio'),
('AMSI Plan Único'),
('AMSTERDAM SALUD S.A. Categoría A'),
('AMSTERDAM SALUD S.A. Categoría B1'),
('AMSTERDAM SALUD S.A. Categoría B2'),
('AMSTERDAM SALUD S.A. Categoría C'),
('AMSTERDAM SALUD S.A. OSRGA- Urgara 40'),
('AMTA Plan único'),
('AMTCYA Plan Único'),
('Amttac (Mutual Trabajadores de Transp. Cargas Cordoba) Plan Medico Obligatorio'),
('AMUPRO Plan básico'),
('AMUPRO Plan maxim'),
('AMUPRO Plan premium'),
('AMUR A'),
('AMUR D2'),
('AMUR JM'),
('AMUR M'),
('AMUR M1'),
('AMUR Plan especial'),
('AMUR S'),
('Andar Plan Básico'),
('Andar Plan Clásico'),
('Andar Plan Especial'),
('Andar Plan Plus'),
('ANDAR (OSVVRA) Básico'),
('ANDAR (OSVVRA) Clásico'),
('ANDAR (OSVVRA) Especial'),
('ANDAR (OSVVRA) Plan Médico Obligatorio'),
('ANDAR (OSVVRA) Plus'),
('ANDESSalud Plan Black'),
('ANDESSalud Plan Gold'),
('ANDESSalud Plan Joven'),
('ANDESSalud Plan Platinum'),
('Apesa Adultos Abierto'),
('Apesa Adultos Cerrado'),
('Apesa Joven'),
('Apesa Mayores'),
('APM Plan único'),
('APOS Administración Provincial de Obra Social Plan único'),
('APPI Red Colegio de Farmaceuticos'),
('APPI Red Ospaca'),
('APPI Red Osvara'),
('APPSI Plan Unico'),
('Apres Global Classic'),
('Apres Global Plus'),
('Apres Global Premium'),
('Apres Plan A'),
('Apres Plan Classic'),
('Apres Plan Corporativo'),
('Apres Plan MQ'),
('Apres Plan Plus'),
('Apres Plan Premium'),
('Apres Plan RS'),
('Apres Plan T'),
('APROSS Plan único'),
('Apsot (Techint) Plan único'),
('APTM (Plantadores de Tabaco de Misiones) Plan Médico Obligatorio'),
('ART Asinac'),
('ART Asociart'),
('ART Berkley'),
('ART Boston'),
('ART Caminos Protegidos'),
('ART CNA'),
('ART Colonia Suiza'),
('ART Experta'),
('ART Federación Patronal'),
('ART Galeno S.A.'),
('ART Horizonte'),
('ART Iapser'),
('ART Interacción'),
('ART Juncal'),
('ART La Holando'),
('ART La Holando (Acc. Pers.)'),
('ART La meridional'),
('ART La Segunda'),
('ART Liderar'),
('ART Mapfre Argentina'),
('ART Mercantil'),
('ART Mutual Rural ART'),
('ART Omint'),
('ART Prevención'),
('ART Prevención (Fdo. Reserva)'),
('ART PROFRUT ART'),
('ART Prome'),
('ART Provincia'),
('ART QBE'),
('ART Reconquista ART'),
('ART SMG ART'),
('ART Swiss Medical'),
('ART Swiss Medical Group'),
('ART Victoria'),
('Arte de Curar Plan Medico Obligatorio'),
('ASE Plan Eco'),
('ASE Plan Eco Plus'),
('ASE Plan Vision'),
('ASE Plan Vision Plus'),
('ASI Salud Plan Exclusive'),
('ASI Salud Plan Master'),
('ASI Salud Plan Senior Plus'),
('ASI -Sanatorio- Plan único'),
('ASIMRA Plan único'),
('ASIO Plan B'),
('ASIO Plan C'),
('ASIO Plan D'),
('ASIO Plan J'),
('ASIO Plan M'),
('Asistir Familia con coseguro'),
('Asistir Familia sin coseguro'),
('ASMEPRIV Asistencia Médica Privada PL5N CME'),
('ASMEPRIV Asistencia Médica Privada Plan AS 100'),
('ASMEPRIV Asistencia Médica Privada Plan AS 110'),
('ASMEPRIV Asistencia Médica Privada Plan AS 120'),
('ASMEPRIV Asistencia Médica Privada Plan AS 200'),
('ASMEPRIV Asistencia Médica Privada Plan AS 300'),
('ASMEPRIV Asistencia Médica Privada Plan CME'),
('ASMEPRIV Asistencia Médica Privada Plan HM'),
('ASMEPRIV Asistencia Médica Privada PMO'),
('ASOC. ARG.MUTUAL DEL MOTOCICLISTA Plan Único'),
('ASOC. MUTUAL 23 DE DICIEMBRE Plan Único'),
('Asociación Argentina de Volantes Plan único'),
('Asociación Médica del Departamento Castellanos Plan Médico Obligatorio'),
('ASOCIACION MUT. SOCIOS CÍRCULO MÉDICO VICTORIA Plan Único'),
('Asociación Mutual 20 de octubre Plan único'),
('ASOCIACION MUTUAL DE PROTECCIÓN FAMILIAR Grupo familiar'),
('ASOCIACION MUTUAL DE PROTECCIÓN FAMILIAR Grupo familiar (paralelo 42)'),
('Asociacion Mutual Semid Plan Medico Obligatorio'),
('Asociacion Mutual Senderos (Ctep) Plan Medico Obligatorio'),
('Asociación Unión Tamberos Plan Medico Obligatorio'),
('Asociaciones de Obras Sociales (A.D.O.S.) Plan único'),
('Asor Salud 100 Especial'),
('Asor Salud Primario'),
('ASPURC Plan Médico Obligatorio'),
('Assist Dent Plan Familiar'),
('Assist Dent Plan Inicial'),
('Assist Dent Plan Premium'),
('Assist Dent Plan Superior'),
('Assist Dent Plan Total'),
('Assistravel Plan único'),
('ASSPE Plan Unico'),
('ASUNT (Universidad Nac Tucuman) Plan Asistencial Solidario'),
('ASUNT (Universidad Nac Tucuman) Plan Médico Obligatorio'),
('ATE Asociación Trabajadores del Estado Plan San Juan'),
('ATRAU Medic Plan único'),
('ATSA Plan Único'),
('AUDITART Plan Único'),
('Avalian Avalian'),
('Avalian CLASICA PLAN 2'),
('Avalian Integral'),
('Avalian Plan Cerca'),
('Avalian Plan Médico Obligatorio'),
('Avalian Plan Único'),
('Avalian Prepago'),
('Avalian Selecta'),
('Avalian Superior'),
('Avera Plan unico'),
('Ayuda Medica Plan Medico Obligatorio'),
('Bancarios Plan Único'),
('Banco Provincia Plan único'),
('Barrido y Limpieza Plan único'),
('BASA Salud Oro'),
('BASA Salud Plata'),
('BASA Salud Platino'),
('Bassi SA Plan Único'),
('Bayres Plan Bayres Plan Plus'),
('Bayres Plan Plan Complementario con coseguro'),
('Bayres Plan Plan Complementario sin coseguro'),
('Bayres Plan Plan Integral con coseguro'),
('Bayres Plan Plan Integral sin coseguro'),
('Bienestar Salud Plan único'),
('BONACORSI Plan Medico Obligatorio'),
('Boreal A2'),
('Boreal A3'),
('Boreal Clásico'),
('Boreal Integral'),
('Boreal Magnun'),
('Boreal Primario'),
('Boreal VIP'),
('Bounous Maquinarias Plan Medico Obligatorio'),
('Bramed Salud Plan Delta'),
('Bramed Salud Plan Génesis'),
('Bramed Salud Plan Golden'),
('Bramed Salud Plan Integral - PMO'),
('Bramed Salud Plan Omega'),
('Bramed Salud Plan Superior'),
('BRINDAR SALUD Plan 100'),
('BRINDAR SALUD Plan 200'),
('BRINDAR SALUD Plan 250'),
('BRINDAR SALUD Plan 300'),
('Bristol Medicine A'),
('Bristol Medicine BM180'),
('Bristol Medicine BM200I'),
('Bristol Medicine BM200P'),
('Bristol Medicine BM400S'),
('Bristol Medicine BM500P'),
('Bristol Medicine Plan BM 200'),
('Bristol Medicine Plan BM 300'),
('Bristol Medicine Plan BM 400'),
('Bristol Medicine Plan BM 500'),
('Bristol Medicine PMC'),
('Bristol Medicine PMO'),
('Britanica Salud Plan Brisa'),
('Britanica Salud Plan Brisa Mas'),
('Britanica Salud Plan Brisa Premium'),
('Britanica Salud Plan Fisherton Británica'),
('Caja de Abogados Plan único'),
('Caja de Escribanos Capital Federal'),
('Caja de Escribanos Plan Único'),
('Caja de Escribanos Provincia de Buenos Aires'),
('Caja de Ingenieros Azul'),
('Caja de Ingenieros Azul Plus'),
('Caja de Ingenieros Plan único'),
('Caja de Ingenieros Verde'),
('Caja de Servicio Sociales Plan Único'),
('caja forense Plan único'),
('Caja Notarial Plan único'),
('Cami Salud CC 1100'),
('Cami Salud CC 145'),
('Cami Salud CC 165'),
('Cami Salud CC 190'),
('Cami Salud Córdoba - 145'),
('Cami Salud Córdoba - CC 1100'),
('Cami Salud Córdoba CC - 165'),
('Cami Salud Córdoba - CC 190'),
('Cami Salud Plan 3.0'),
('Cami Salud Plan 40/40'),
('Cami Salud Plan Complementario'),
('Cami Salud Plan Dorado'),
('Cami Salud Plan Elección'),
('Cami Salud Plan Joven'),
('Cami Salud Plan Oscep'),
('Cami Salud Plan Oscep 100'),
('Cami Salud Plan S/C'),
('Cami Salud Plan Universitario'),
('CAMIF Bono de consulta afiliados a IOMA'),
('CAMIF Descuento a pacientes afiliados a PAMI'),
('CAMIF Descuento otras obras sociales'),
('CAMIF Particular'),
('Camioneros Plan Único'),
('CAMPSIC swiss medical'),
('CAMPSIC Visitar'),
('CAPS Centros de Atención Primaria de la Salud Plan Único'),
('Cardinal Assistance Plan único'),
('CASA Bayres 1001'),
('CASA Bayres 3001'),
('CASA Bayres 4001'),
('CASA Casa 2001'),
('CASA Casa'),
('CASA Casa Bayres'),
('CASA CASA NOBEL'),
('CASA casaBAS'),
('CASA casaMED'),
('CASA casaPLUS'),
('CASA Coseguro Casa'),
('CASA Jubilados y Pensionados'),
('CASA Plan Integral'),
('CASA Plan Parcial'),
('CASA Programa Joven'),
('Casa Nicolas Servicios Sociales Plan Medico Obligatorio'),
('Casa Salud Bayres 1001'),
('Casa Salud Bayres 2001'),
('Casa Salud Bayres 3001'),
('Casa Salud Bayres 4001'),
('Casa Salud CASA'),
('Casa Salud Casabas'),
('Casa Salud Casamed'),
('Casa Salud Casaplus'),
('Casa Salud Coseguro Casa'),
('Casa Salud Plan Integral'),
('Casa Salud Plan Parcial'),
('Casa Salud Programa Joven'),
('CEA - San Pedro Plan Unico'),
('CEL SALUD Plan único'),
('Celius Salud Plan único'),
('CELMA SRL (Pilotos de competencias de Automovilismo, Karting, Motos) Plan Unico'),
('Cemiba Plan unico'),
('CEMIC 6010'),
('CEMIC 6020'),
('CEMIC 6030'),
('CEMIC 6040'),
('CEMIC 6050'),
('CEMIC 6060'),
('CEMIC 6070'),
('CEMIC Plan 1300 y Derivados'),
('CEMIC Plan 200 y Derivados'),
('CEMIC Plan 300 y Derivados'),
('CEMIC Plan 400 y Derivados'),
('CEMIC Plan 500 y Derivados'),
('CEMIC Plan 5050'),
('CEMIC Plan 600 y Derivados'),
('CEMIC Plan 6000'),
('CEMIC Plan 700 y Derivados'),
('CEMIC Plan 8000'),
('CEMLA Plan Único'),
('Centro Asistencial ADVANCE'),
('Centro Asistencial ADVANCE ORO'),
('Centro Asistencial PREMIUM'),
('Centro Gallego Plan Unico'),
('Centro Gallego Plan único'),
('CENTRO MEDICO HELGUERA Plan unico'),
('CENTRO MEDICO HELGUERA Plan único'),
('CENTRO MEDICO PUEYRREDON ALFA'),
('CENTRO MEDICO PUEYRREDON BETA'),
('CENTRO MEDICO PUEYRREDON Centro Medico Pueyrredon'),
('CENTRO MEDICO PUEYRREDON GAMMA'),
('CEPRIMED Plan único'),
('Ceramistas Plan único'),
('CIBA Plan Unico'),
('CIENC / ECONOMICAS Plan único'),
('CIENCIAS ECONOMICAS Plan Único'),
('CIMA Roble Plus'),
('CIMA INTEGRAL S.A. Arrayán'),
('CIMA INTEGRAL S.A. CIMO'),
('CIMA INTEGRAL S.A. Master'),
('CIMA INTEGRAL S.A. Ombu'),
('CIMA INTEGRAL S.A. Roble'),
('CIMA INTEGRAL S.A. Sauce'),
('CIMA INTEGRAL S.A. Vip'),
('CIMAC Plan único'),
('CIMESA (Circulo Medico Salud) Plan Medico Obligatorio'),
('Circulo Abogados Plan Único'),
('Circulo medico Plan único'),
('Círculo Médico de Vicente López Plan CM 100'),
('Círculo Médico de Vicente López Plan CM 25'),
('Círculo Médico de Vicente López Plan CM 50'),
('City salud plan unico'),
('CLERO ARGENTINO Plan único'),
('Clero San Pedro Plan único'),
('Clio Plan Único'),
('Cm-Salud CM 100'),
('Cm-Salud CM 25'),
('Cm-Salud CM 50'),
('cmc Plan unico'),
('COBENSIL S.A Plan único'),
('Cober CLASSIC X'),
('Cober TAYLORED'),
('Cober WAGON'),
('Cober X'),
('Cobermed 1001'),
('Cobermed 2001'),
('Cobermed Plan Basico'),
('Cobermed Plan Clásico'),
('Cobermed Plan Joven'),
('Cobermed Plan Mayor'),
('COBERTEC Plan medico obligatorio'),
('Cobertura de Salud De Bell Ville Plan Único'),
('COBERTURA MEDICA DEPORTIVA Plan Único'),
('Cocheria Rio Cuarto Plan Médico Obligatorio'),
('Cogas Plan Medico Obligatorio'),
('Colegio de Escribanos OSCE'),
('Colegio de Escribanos CABA Col. Cap'),
('Colegio de Escribanos CABA Plan B'),
('Colegio de Escribanos de Salta Plan Único'),
('Colegio de Escribanos Prov. Bs. As. Plan Medico Obligatorio'),
('ColMed Colegio Médico Plan i300'),
('ColMed Colegio Médico Plan i600'),
('ColMed Colegio Médico Plan v200'),
('COMEDICA Plan Único'),
('Comei Plan único'),
('COMI Plan CC'),
('COMI Plan CN'),
('COMI Plan CP'),
('COMI Plan CS'),
('COMI Plan FC'),
('COMI Plan FN'),
('COMI Plan FS'),
('COMI Plan RC'),
('COMI Plan RT'),
('Conexion Salud Red de prestadores'),
('Conferencia Episcopal Argentina Plan único'),
('Consalud Plan familiar'),
('Consalud Plan óptimo'),
('Consalud Plan Premiun'),
('Consalud Plan Superador PSSA integral 30'),
('Consalud Plan Único'),
('Consolidar Plan único'),
('CONSULMED Plan único'),
('COOPERATIVA DE SEGUROS LIMITADA Plan unico'),
('Cooperativa Los del Pago Plan Unico'),
('Cooperativa Oro Verde Plan único'),
('Cooperativa SERCOP Plan Unico'),
('Cooperativa Telefónica Tostado Plan Medico Obligatorio'),
('CORA Plan único'),
('CORDOBA DENTAL Plan único'),
('Corpomedicin Salud Plan Único'),
('Corporación Asistencial Plan único'),
('Corporación Médica 101'),
('Corporación Médica 202'),
('Corporación Médica 303'),
('Corporación Médica 404'),
('Corporación Médica 505'),
('Corporación Médica 606'),
('Corporación Médica 707'),
('Corporación Médica 808'),
('Corte Suprema de Justicia Plan único'),
('Cosecha Salud Plan único'),
('Cover Salud Plan 801'),
('Cover Salud Plan 803'),
('Cover Salud Plan 804'),
('CPCE Cordoba Plan único'),
('CPCES Caja de Seguridad Social Plan Básico'),
('CPCES Caja de Seguridad Social Plan Coseguro'),
('CPCES Caja de Seguridad Social Plan Integral'),
('CPCES Caja de Seguridad Social Plan Joven'),
('CPCES Caja de Seguridad Social Planes Plus'),
('CrisolMed Plan Bronze'),
('CrisolMed Plan Gold'),
('CrisolMed Plan Joven Gold'),
('CrisolMed Plan Platinum'),
('CrisolMed Plan Silver'),
('CTM (Camara del Tabaco Misiones) Plan Médico Obligatorio'),
('Cynthios Salud Plan Unico'),
('DAMSU Plan Único'),
('DAS Plan Único'),
('DASMI Luján'),
('DASMI Plan Único'),
('DASPU (Obra Social Universitaria) Plan Médico Obligatorio'),
('Dasu Plan único'),
('Dasuten Plan Único'),
('DEL PLATA SALUD Plan único'),
('Demi Salud Azul Plus'),
('Demi Salud Demi O-P'),
('Diba Plan Único'),
('DIBPFA - PERSONAL DE LA FUERZA AEREA Plan único'),
('DIVISION SERVICIOS SOCIALES DE LA POLICIA DE SAN JUAN Plan Unico'),
('DKV Seguro Médico DKV Integral Classic'),
('DKV Seguro Médico DKV Integral Complet'),
('DKV Seguro Médico DKV Integral Élite'),
('DKV Seguro Médico DKV Mundisalud Classic'),
('DKV Seguro Médico DKV Mundisalud Complet'),
('DKV Seguro Médico DKV Profesional Asistencia primaria'),
('DKV Seguro Médico DKV Top Health'),
('DKV Seguro Médico Famedic Plus'),
('Doctored Global'),
('Doctored Integral'),
('Doctored Plan 1000'),
('Doctored Plan 2000'),
('Doctored Plan 3000'),
('Doctored Plan 500'),
('Doctored Premium'),
('DOCTORED MERCADO CENTRAL Plan MC 200'),
('DOCTORED MERCADO CENTRAL Plan MC ATE'),
('DOCTORED PLAN 1000 Plan único'),
('DOCTORED PLAN 3000 Plan único'),
('DOCTORED PLAN 500 Osamoc'),
('DOCTORED PLAN 500 Osbara'),
('DOCTORED PLAN 500 Oseiv'),
('Domin Salud Alfa'),
('Domin Salud Beta'),
('Domin Salud Complementario Apoc - Mume'),
('Domin Salud Delta'),
('Domin Salud Epsilon'),
('Domin Salud Gamma'),
('Domin Salud Gamma'),
('Domin Salud Zeta'),
('DOS - Dirección Obra Social Plan Unico'),
('DOSEM (Empleados Municipales) Plan Médico Obligatorio'),
('DOSEP Plan San Luis'),
('DOSPU Plan único'),
('Dosuba Plan Estudiantil'),
('Dosuba Plan Graduados'),
('Dosuba Plan Médico Obligatorio'),
('Dosuba Plan único'),
('Eclesiástica San Pedro Plan Único'),
('Elevar - Pasteleros Plan único'),
('EMA SALUD Plan Unico'),
('emedic Plan Basico'),
('Emergencias 100'),
('Emergencias 200'),
('Emergencias 605'),
('Emerger Plan Único'),
('Empredimed Plan Medico Obligatorio'),
('En El Hogar S.A. Plan Unico'),
('ENDOCTER GLOBAL'),
('ENDOCTER INTEGRAL'),
('ENDOCTER TOTAL'),
('Energia Salud APJ'),
('Energia Salud Oro'),
('Energia Salud Oro Prepago'),
('Energia Salud Plata'),
('Energia Salud Plata Prepago'),
('Energia Salud Platino'),
('Energia Salud Platino Prepago'),
('Enrique Serra Servicios Sociales Plan único'),
('ENSALUD Delta'),
('ENSALUD Gamma'),
('ENSALUD Krono'),
('ENSALUD Plan único'),
('ENSALUD Quantum'),
('Esencial E'),
('Esencial Esencial.ar'),
('Esencial Grupo Oroño'),
('Esencial MTA'),
('Esencial Plata'),
('Esencial Platino'),
('Espora Salud Juvenil'),
('Espora Salud Maternidad'),
('Espora Salud Plan 600'),
('Espora Salud Planes 1 y 2'),
('Etica Salud Plan único'),
('Europ Assistance Plan único'),
('Eurosalud Plan Único'),
('Eurosistemas S.A. Plan Único'),
('Exce Salud ExceSalud 1100'),
('Exce Salud ExceSalud 2200'),
('Exce Salud ExceSalud Dignity'),
('Exce Salud Plan Proteger Vidas'),
('EXEL MED Plan único'),
('FAA Plan Único'),
('Family Group Plan único'),
('FAMYL Plan único'),
('FATFA OSPF (Farmacia) Plan Único'),
('FE SALUD 60'),
('FE SALUD AMBULATORIO'),
('FE SALUD GENTE JOVEN'),
('FE SALUD OBRA SOCIAL'),
('FE SALUD PLAN A'),
('FE SALUD PLAN B'),
('FE SALUD PLAN C'),
('FE SALUD PLAN DORADO'),
('FE SALUD PLAN INFANTIL'),
('FE SALUD TOTAL'),
('FE SALUD UNIVERSITARIOS'),
('FE SALUD VITAL'),
('Fe Salud (Fesalud) A'),
('Fe Salud (Fesalud) C'),
('Fe Salud (Fesalud) DF Dorado Full'),
('Fe Salud (Fesalud) GJ Gente Joven'),
('Fe Salud (Fesalud) IN Infantil'),
('Fe Salud (Fesalud) OS Obra Social'),
('Fe Salud (Fesalud) S Social'),
('Fe Salud (Fesalud) V Vital'),
('Federación Médica (Femesfe) Plan Medico Obligatorio'),
('Federación Patronal Accidentes Personales'),
('FEDERADA 25 DE JUNIO Plan 1'),
('FEDERADA 25 DE JUNIO Plan 2'),
('FEDERADA 25 DE JUNIO Plan 4000'),
('FEDERADA 25 DE JUNIO Plan único'),
('FEDERADA SALUD 1000+'),
('FEDERADA SALUD 5000'),
('FEDERADA SALUD 7'),
('FEDERADA SALUD A'),
('FEDERADA SALUD B'),
('FEDERADA SALUD F'),
('FEDERADA SALUD Familia'),
('FEDERADA SALUD L90'),
('FEDERADA SALUD M'),
('FEDERADA SALUD P'),
('FEDERADA SALUD Plan 1000'),
('FEDERADA SALUD Plan 2000'),
('FEDERADA SALUD Plan 3000'),
('FEDERADA SALUD Plan 4000'),
('FEDERADA SALUD Plan esp'),
('FEDERADA SALUD Plan Joven'),
('FEDERADA SALUD Plan Nacional 1'),
('FEDERADA SALUD Plan Regional 2'),
('FEDERADA SALUD Plan único'),
('FEDERADA SALUD R'),
('FEDERADA SALUD R1'),
('FEDERADA SALUD S'),
('Femeba Avellaneda'),
('Femeba Berazategui'),
('Femeba Florencio Varela'),
('Femeba General Sarmiento'),
('Femeba Lanús'),
('Femeba OSPRERA'),
('Femeba OSTEL'),
('Femeba Plan Único'),
('Femeba Quilmes'),
('Femechaco Plan único'),
('Femedica Azul'),
('Femedica Estilo'),
('Femedica Estilo Joven'),
('Femedica Familia'),
('FEMESA Dorado pack'),
('FEMESA Familiar OS'),
('FEMESA Integral'),
('FEMESA Privilegio'),
('FEMESA Total'),
('FIDEROS Plan único'),
('FORD Plan único'),
('Formed Plan 100'),
('Formed Plan 1000'),
('Formed Plan 300'),
('Formed Plan 500'),
('Formed Plan MTS'),
('FOSDIC DELTA'),
('FOSDIC KRONO'),
('FOSDIC QUANTUM'),
('FOTOGRAFOS Plan único'),
('Francisco Serra Servicios Sociales Plan único'),
('FSST TECHINT Plan Apsot 1'),
('FSST TECHINT Plan Apsot 11'),
('Fuerza Aerea Plan Único'),
('FUTBOLISTAS Plan único'),
('G7 Salud Plan único'),
('Galeno 220'),
('Galeno 330'),
('Galeno 440'),
('Galeno 550'),
('Galeno Adherentes'),
('Galeno Azul'),
('Galeno Blanco'),
('Galeno Oro'),
('Galeno OSSOS'),
('Galeno Plata'),
('Galeno Consulting Group Plan único'),
('GAPRESA S.A Plan único'),
('GEA Gea 100'),
('GEA Gea 3.0'),
('GEA Gea 300'),
('GEA Gea 310'),
('GEA GEA 350'),
('GEA GEA 400'),
('GEA GEA 500'),
('GEA GEA C+'),
('GEA Gea Mill'),
('GEA GEA ZERO'),
('GEMEPER SA Plan Único'),
('Generar Salud Plan único'),
('Genesen A1'),
('Genesen A2'),
('Genesen A3'),
('Genesen A4'),
('Genesen A5'),
('Genesen B2'),
('Genesen G400'),
('Genesen H1'),
('Genesen H2'),
('Genesen H3'),
('Genesen H4'),
('Genesen OS'),
('Genesen OS2'),
('Genesen OS2I'),
('Genesen OS2S'),
('Genesen Plan G100'),
('Genesen Plan G200'),
('Genesen Plan G300'),
('Genesen PP'),
('Genesen R1'),
('Génesis Plan único'),
('GEPREMED S.A Plan Único'),
('Gerdanna Salud Plan Único'),
('Gerenciadora Salud Plan Integrador'),
('Gerenciadora Salud Plan Medico Obligatorio'),
('Gerenciadora Salud Plan Platino'),
('Gerenciadora Salud Plan Superior'),
('GERMED S.A. Plan Único'),
('GM Salud Plan Oro'),
('GM Salud Plan Plata'),
('GM Salud Plan PMO'),
('GMA Salud Plan Unico'),
('GRASSI SS Plan Médico Obligatorio'),
('Griff Salud Plan Unico'),
('Grupo Asegurador La Segunda Accidentes personales'),
('Grupo Pretoq MED GPM Plan Médico Obligatorio'),
('Grupo Roisa Plan Cuidarte'),
('Grupo Roisa Plan Cuidarte Plus'),
('Grupo San Nicolas B 2100'),
('Grupo San Nicolas B 3100'),
('Grupo San Nicolas B 4100'),
('GRUPO SANATORIO BRITÁNICO (Salud Rosario) Plan Unico'),
('Harineros Plan Medico Obligatorio'),
('Health Medical Plan L'),
('Health Medical Plan P'),
('Health Medical Plan T'),
('Hemisferio Salud OSADRA'),
('Hemisferio Salud OSALARA Alta complejidad'),
('Hemisferio Salud OSALARA Juegos de Azar'),
('Hemisferio Salud OSALARA PMO'),
('Hemisferio Salud OSPEP'),
('Hemisferio Salud OSPIC (caucho)'),
('Higea Plan h1000'),
('Higea Plan h2000'),
('Hominis 300'),
('Hominis 400'),
('Hominis AQUA'),
('Hominis AQUA MAS'),
('Hominis AQUA MAS MUGESBA'),
('Hominis H 3.0'),
('Hominis H1.0'),
('Hominis H3.0 C'),
('Hominis H3.0 EMP'),
('Hominis H3.0 T'),
('Hominis M-N'),
('Hominis PMOD MUGESBA'),
('Hominis S-N'),
('Hominis SG 1.0'),
('Hominis SG 2.0'),
('Hominis SGO MUGESBA'),
('Hominis SH-N'),
('Hominis T-N'),
('Hominis TH-N'),
('Hominis VIT A'),
('Hominis VITA'),
('Hominis VITA EMP.'),
('Hominis VITA MAS'),
('Hominis VITA MAS MUGESBA'),
('Hominis VITA MUGESBA'),
('Hospital Aleman 10ORO'),
('Hospital Aleman 11J'),
('Hospital Aleman 150'),
('Hospital Aleman 15A'),
('Hospital Aleman 1A'),
('Hospital Aleman 1E'),
('Hospital Aleman 1EA'),
('Hospital Aleman 4A'),
('Hospital Aleman 5A'),
('Hospital Aleman 8A'),
('Hospital Aleman A2'),
('Hospital Aleman ASE'),
('Hospital Aleman Dar 15'),
('Hospital Aleman Dar 3'),
('Hospital Aleman ED. Emp. Dir'),
('Hospital Aleman Estádar'),
('Hospital Aleman Joven'),
('Hospital Aleman Kinderplan'),
('Hospital Aleman Kinderplan A6'),
('Hospital Aleman Kofar Azul'),
('Hospital Aleman Kofar Rojo'),
('Hospital Aleman Kofar Verde'),
('Hospital Aleman KPA'),
('Hospital Aleman Línea Evolución'),
('Hospital Aleman M11'),
('Hospital Aleman Plan 1'),
('Hospital Aleman Plan 11'),
('Hospital Aleman plan 150'),
('Hospital Aleman Plan 2'),
('Hospital Aleman Plan 6'),
('Hospital Aleman Plan 8'),
('Hospital Aleman Plan 9'),
('Hospital Aleman Plan A'),
('Hospital Aleman Plan A3'),
('Hospital Aleman Plan A6'),
('Hospital Aleman Plan A7'),
('Hospital Aleman Plan AJ'),
('Hospital Aleman Plan Classic'),
('Hospital Aleman Plan J'),
('Hospital Aleman Plan joven max'),
('Hospital Aleman Plan joven plus'),
('Hospital Aleman Plan medico (empadronados)'),
('Hospital Aleman Plan oro'),
('Hospital Aleman Plan S'),
('Hospital Aleman Premium'),
('Hospital Aleman Siemens'),
('Hospital Austral ACES PLUS'),
('Hospital Austral Clásico 2020'),
('Hospital Austral Clásico 2020 ACES'),
('Hospital Austral Clásico 4030'),
('Hospital Austral Clásico 4040'),
('Hospital Austral Joven 3010'),
('Hospital Austral Mi Médico 1100'),
('Hospital Austral Mi Médico 1202'),
('Hospital Austral Mi Médico 3030'),
('Hospital Austral Mi Médico ACES'),
('Hospital Austral Plan Clásico 2000'),
('Hospital Austral Plan Clásico 2020'),
('Hospital Austral Plan Mi Médico'),
('Hospital Austral Plan Mi Médico 1201'),
('Hospital Austral PMO'),
('Hospital Britanico Hospital Britanico'),
('Hospital Britanico Plan Children'),
('Hospital Britanico Plan Corporativos'),
('Hospital Britanico Plan En relacion de dependencia'),
('Hospital Britanico Plan Grupo Familiar'),
('Hospital Britanico Plan Joven'),
('Hospital Britanico Plan Monotributistas'),
('HOSPITAL DESCENTRALIZADO DOCTOR GUILLERMO RAWSON Plan Unico'),
('Hospital Italiano Plan 2002 Global'),
('Hospital Italiano Plan Familiar o Senior Global'),
('Hospital Italiano Plan Infantil Global'),
('Hospital Italiano Plan Joven Global'),
('Hospital Italiano Plan Máximo Global'),
('Hospital Italiano Plan Mayor Global'),
('Hospital Italiano Plan Universitario Global'),
('Hospital Sirio Libanes Plan Único'),
('I.P.S. de Salta Plan Único'),
('I.S.SEGUROS Plan Único'),
('Iamip Basico'),
('Iamip Clasico'),
('Iamip Oro'),
('Iamip Platino'),
('IAPOS IAPOS Accidente de Trabajo'),
('IAPOS IAPOS Accidente de Transito'),
('IAPOS Plan único'),
('IASEP Plan Único'),
('Imagen En Salud ISSPICA - Plan Medico Obligatorio'),
('IMAS Plan único'),
('Immyn Plan único'),
('IMPS Instituto Municipal de Prevención Social Plan único'),
('Incluir Salud (PROFE) Plan único'),
('INGENIEROS Plan único'),
('INSSSEP Plan único'),
('Instituto de Seguridad Social del Neuquen Neuquén'),
('Instituto de Seguro de Jujuy Plan Unico'),
('Instituto de seguro de Jujuy (ISJ) Plan único'),
('Instituto Médico Labor Plan Medico Obligatorio'),
('Integración Médica Plan único'),
('INTEGRAL Arrayán'),
('INTEGRAL Ceibo'),
('INTEGRAL Gilsa Srl'),
('INTEGRAL Plan único'),
('INTEGRAL Roble'),
('Intermedicina Plan unico'),
('IOMA IO Plan A'),
('IOMA IO Plan B'),
('IOMA Plan 056'),
('IOMA Plan 252'),
('IOMA Plan 371'),
('IOMA Plan 412'),
('IOMA Plan 480'),
('IOMA Plan 749'),
('IOMA Plan 756'),
('IOMA Plan 805'),
('IOMA Plan 840'),
('IOMA Plan 861'),
('IOMA Plan Único'),
('IOSCor Plan Medico Obligatorio'),
('IOSCor Plan PLAMIN'),
('IOSE Plan único'),
('Iosep Plan único'),
('IOSFA (Instituto de O.S Fuerzas Armadas) Plan Medico Obligatorio'),
('Iosper Plan unico'),
('IPROSS Plan Único'),
('IPS Instituto de Previsión Social Plan único'),
('IPS  Instituto Provincial de Salud de Salta Plan Unico'),
('ISalud AMIS'),
('ISalud AZUL'),
('ISalud OMA'),
('ISalud Plan Medico Obligatorio'),
('ISalud PREMIUM'),
('ISalud SALUD CENTRAL'),
('ISalud SC-30'),
('ISalud SC-70'),
('ISSN Plan único'),
('ISSUNCAus Plan único'),
('ISSUNNE (Instituto Servicios Sociales) Plan Medico Obligatorio'),
('ISSYS Plan Seros Chubut'),
('ISSYS Plan  Seros Vital'),
('ITALMEDIC Plan Lazio'),
('ITALMEDIC Plan Milano'),
('ITALMEDIC Plan Nob'),
('ITALMEDIC Plan Veneto'),
('Itati Plan único'),
('ITER Medicina Red de Prestadores'),
('JERARQUICOS SALUD Jerarquicos Salud'),
('JERARQUICOS SALUD Plan Joven'),
('JERARQUICOS SALUD PMI'),
('JERARQUICOS SALUD PMI 2000'),
('JERARQUICOS SALUD PMI 2886'),
('JERARQUICOS SALUD PMI 3000'),
('Jockey Club Plan Único'),
('La Pequeña Familia Plan Celeste'),
('La Pequeña Familia Plan Celeste Joven'),
('La Pequeña Familia Plan Dorado'),
('La Pequeña Familia Plan Integral'),
('La Pequeña Familia Plan Verde'),
('La Ras Plan unico'),
('Laboumed Plan Azul'),
('Laboumed Plan Dorado'),
('Leal Médica Plan 100'),
('Leal Médica Plan 1000'),
('Leal Médica Plan 500'),
('Ley 5110 Plan Unico'),
('LPF Plan Único'),
('Lugones Salud Plan LS40'),
('Luis Pasteur J'),
('Luis Pasteur Millen'),
('Luis Pasteur N SIEMENS'),
('Luis Pasteur P SIEMENS'),
('Luis Pasteur Plan  C'),
('Luis Pasteur Plan E'),
('Luis Pasteur Plan Especial'),
('Luis Pasteur Plan L'),
('Luis Pasteur Plan M'),
('Luis Pasteur Plan N'),
('Luis Pasteur Plan Novo'),
('Luis Pasteur Plan Ns'),
('Luis Pasteur Plan P'),
('Luis Pasteur Plan Ps'),
('Luis Pasteur Plan S'),
('Luis Pasteur Plan V'),
('Luis Pasteur Platea'),
('Luis Pasteur Pmi'),
('Luis Pasteur S SIEMENS'),
('Luz Médica -OSTEE- Plan único'),
('Luz y Fuerza Plan único'),
('M.O.A 190'),
('M.O.A 200'),
('M.O.A 240'),
('M.O.A 250'),
('M.O.A 290'),
('M.O.A 300'),
('M.O.A Pleno AOA'),
('M.O.A Pleno JOVEN'),
('M.O.A Mutual Odontológica Argentina Plan Mutual'),
('M.O.A Mutual Odontológica Argentina Plan Pleno'),
('M.O.A Mutual Odontológica Argentina Plan Protección profesional'),
('madereros Plan único'),
('Mandar Salud D.A.S.'),
('Mandar Salud Das Congreso de la Nacion'),
('Mandar Salud Ospip'),
('Mandar Salud Osprera'),
('Mandar Salud Plan San Jose'),
('MAPFRE- Ibero Asistencia Plan Unico'),
('Mapfre Salud Plan 100'),
('Mapfre Salud Plan 200'),
('Mapfre Salud Plan 300'),
('Maradona Salud Plan Clasico'),
('Maradona Salud Plan Superior'),
('Maria Auxiliadora Salud Plan Base'),
('Maria Auxiliadora Salud Plan Plus'),
('Med Point S.A Plan Médico Obligatorio'),
('Medical Corporative Trade GOLD-P'),
('Medical Corporative Trade M-R 2013'),
('Medical Corporative Trade MAYOR 2013'),
('Medical Corporative Trade MCT-200'),
('Medical Corporative Trade Plan único'),
('Medical Giss Plan Azul'),
('Medical Giss Plan Plus'),
('Medical Giss Plan Plus+'),
('Medical Group S.A Plan Medico Obligatorio'),
('Medical-s Golden'),
('Medical-s Joven'),
('Medical-s Max'),
('Medical-s Plan MS2'),
('Medical-s Plan MS2J'),
('Medical-s Plan MS3'),
('Medical-s Plus'),
('Medical Work Plan Único'),
('Medicall Express Plan único'),
('Medicals BB'),
('Medicals BPB'),
('Medicals CS'),
('Medicals Dorada'),
('Medicals General'),
('Medicals INTEGRAL PLUS'),
('Medicals MD150'),
('Medicals MD250'),
('Medicals MD350'),
('Medicals MD450'),
('Medicals MN100'),
('Medicals MN210'),
('Medicals MN300'),
('Medicals MNPMO'),
('Medicals MS100'),
('Medicals MS120'),
('Medicals MS130'),
('Medicals MS2'),
('Medicals MS200'),
('Medicals MS210'),
('Medicals MS300'),
('Medicals MSPMO'),
('Medicals OSFE INTEGRAL'),
('Medicar Work Plan Unico'),
('Medicardio Plan Único'),
('MEDICARWORK Plan Unico'),
('Medicenter  Salud 3.1 Plan JR'),
('Medicenter  Salud 3.2 Plan R1 – R2'),
('Medicenter  Salud 3.3 Plan RN'),
('Medicenter  Salud 3.4 Plan Q1 – Q2 Quality'),
('Medicenter  Salud 3.5 Plan 01 – 01 Omega'),
('Medicien Azul'),
('Medicien BM 200'),
('Medicien BM 300'),
('Medicien BM 400'),
('Medicien BM 500'),
('Medicien Gris'),
('Medicina Argentina Plan Salus'),
('Medicina Empresarial Plan único'),
('Medicina y Salud Plan único'),
('Medicus Azul'),
('Medicus Azul Galicia'),
('Medicus Azul Legislatura'),
('Medicus Azul Marolio'),
('Medicus Azul Maxiconsumo'),
('Medicus Azul Peugeot'),
('Medicus Azul Siemens'),
('Medicus Blanco'),
('Medicus Blanco Corporativo'),
('Medicus Celeste'),
('Medicus Celeste Galicia'),
('Medicus Celeste Marolio'),
('Medicus Celeste Maxiconsumo'),
('Medicus Celeste Peugeot'),
('Medicus CENTROS MEDICUS'),
('Medicus Citroen'),
('Medicus CORPORATE'),
('Medicus Corporativo'),
('Medicus Empresas'),
('Medicus FAMILY CARE'),
('Medicus Family Care One'),
('Medicus Family Flex'),
('Medicus Fuerzas de seguridad MS1'),
('Medicus Fuerzas de seguridad MS2'),
('Medicus Gris Corporate'),
('Medicus Gris Corporativo'),
('Medicus Gris Legislatura'),
('Medicus Integra 2'),
('Medicus Mc Integral'),
('Medicus Medico de Cabecera'),
('Medicus MS1'),
('Medicus MS2'),
('Medicus MZ Zonal Peugeot'),
('Medicus Naranja Plan Integra2'),
('Medicus O. S. FORD'),
('Medicus ONE R'),
('Medicus Plan Integra 3'),
('Medicus Plan Joven'),
('Medicus Plan ME'),
('Medicus Plan Mujer'),
('Medicus Plan Mz'),
('Medife Azul'),
('Medife Blanco'),
('Medife Bronce'),
('Medife Cobre'),
('Medife Juntos'),
('Medife Oro'),
('Medife Plata'),
('Medife Platinum'),
('Medife Verde'),
('Medife Voluntario'),
('Medin (SASMA) Global'),
('Medin (SASMA) Joven'),
('Medin (SASMA) Medicals'),
('Medin (SASMA) Medin'),
('Medin (SASMA) Plan Optimo'),
('Medin (SASMA) Platino'),
('MEDINTH (Lab. Bago) Plan Unico'),
('Medipar Plan único'),
('MediSalud Plan Unico'),
('MedLink Plan Clasico'),
('MedLink Plan Dorado'),
('MedLink Plan Platino'),
('MedLink Plan PMO'),
('MedLink Plan único'),
('MEDYCIN CLASSIC'),
('MEDYCIN VIP'),
('MePLIFE Plan Básico'),
('MePLIFE Plan Full'),
('MePLIFE Plan Intermedio'),
('MET Medicina Privada MTA +'),
('MET Medicina Privada MTB +'),
('MET Medicina Privada MTC +'),
('Milkaut Plan Unico'),
('Minerva Plan único'),
('MITA MITA'),
('MOLINEROS Plan único'),
('Molineros Zona Plan Médico Obligatorio'),
('MuDAP Plan único'),
('Municipales Plan único'),
('Municipalidad de Santiago del Estero Plan único'),
('Mutual 31 de Agosto Plan Medico Obligatorio'),
('Mutual Acindar Plan Sol'),
('Mutual Acindar Plan Único'),
('Mutual Amemt Plan Medico Obligatorio'),
('Mutual Argus Salud Plan Médico Obligatorio'),
('Mutual BPC (Banco Prov. Cordoba) Plan Medico Obligatorio'),
('Mutual de empleados Públicos Plan Único'),
('Mutual de escribanos Plan único'),
('Mutual de Suboficiales Retirados Plan Medico Obligatorio'),
('Mutual del Agua y Energía Plan único'),
('Mutual Maestra Plan Medico Obligatorio'),
('Mutual Médica AM-COOP'),
('Mutual Médica Asistencia Familiar'),
('Mutual Médica Azul 100'),
('Mutual Médica Azul 80'),
('Mutual Médica Azul'),
('Mutual Médica Estudiante'),
('Mutual Médica Familia Transportista'),
('Mutual Médica Joven'),
('Mutual Médica Medicoop'),
('Mutual Médica Plan Familia'),
('Mutual Médica Plan Joven 10'),
('Mutual Médica Plan Joven Plus'),
('Mutual Médica Plan Platinum'),
('Mutual Médica Plan Sol'),
('Mutual Médica Plan University'),
('Mutual Médica PRO-Médico'),
('Mutual Médica PRO-Salud'),
('Mutual Médica S 100 especial'),
('Mutual Médica S 200 full'),
('Mutual Médica Sol Transportista'),
('Mutual Médica Suma Mix'),
('Mutual Médica Verde'),
('Mutual Médica Río Cuarto Plan Azul'),
('Mutual Médica Río Cuarto Plan Verde'),
('Mutual Pampeana Plan Único'),
('Mutual Personal Banco de la Pampa Plan Medico Obligatorio'),
('Mutual Policial Neuquen Plan único'),
('Mutual Sabatini Plan Único'),
('Mutual Socorros Mutuos Coronda Plan Medico Obligatorio'),
('MUTUAL SOLIDARIA SALUD Plan único'),
('Mutualyf Plan Medico Obligatorio'),
('NATIVA SALUD Plan único'),
('NATIVUS Plan Unico'),
('Nivel Salud Plan único'),
('NO Plan Unico'),
('NO Plan Unico'),
('NO Plan Unico'),
('Nobis B200'),
('Nobis B300'),
('Nobis N200'),
('Nobis N400'),
('Nobis N500'),
('Nordica Salud Basic'),
('Nordica Salud Coporativo'),
('Nordica Salud Premium'),
('Nordica Salud Vip'),
('Norte beneficios Plan único'),
('Nubial Plan Clasico'),
('Nubial Plan Qualitas'),
('Nubial Plan único'),
('Nubial Quality Simeco'),
('NUEVA MUTUAL DE SERVICIOS NU.MU.SE Plan Básico'),
('NUEVA MUTUAL DE SERVICIOS NU.MU.SE Plan Mayor'),
('OAM - Obra Asistencial Mutual de Mar del Plata Plan Azul'),
('OAM - Obra Asistencial Mutual de Mar del Plata Plan Verde'),
('Obra Social con descuento Bristol'),
('Obra Social con descuento CASA'),
('Obra Social con descuento IOMA'),
('Obra Social con descuento Medicus'),
('Obra Social con descuento Medife'),
('Obra Social con descuento OSDE'),
('Obra Social con descuento Otra'),
('Obra Social con descuento PAMI'),
('Obra Social con descuento Prevención Salud'),
('Obra Social con descuento Sancor Salud'),
('Obra Social Conductores Camioneros - Río Negro Plan Unico'),
('Obra Social de Actores Directos'),
('Obra Social de Actores Monotributistas'),
('Obra Social de Actores Plan Actores'),
('Obra Social de Actores Plan Medico Obligatorio'),
('Obra Social de Actores Plan Universal'),
('OBRA SOCIAL DE CONDUCTORES CAMIONEROS CHUBUT Plan Único'),
('Obra Social de Guincheros y Maquinistas de Gruas Moviles Plan Único'),
('Obra Social de la Carne (O.S.FED. GREM de la carne) Plan Médico Obligatorio'),
('Obra social de seguros Plan unico'),
('Obra social de universidad Plan unico'),
('Obra Social Instituto Plan Único'),
('Obra Social Instituto Plan Único'),
('Obra Social Patrones de Cabotaje (OSPACARP) Especial'),
('Obra Social Patrones de Cabotaje (OSPACARP) Plan Unico'),
('Obra Social Patrones de Cabotaje (OSPACARP) Superior'),
('Obra Social Personal Gráfico OSPG Plan único'),
('Obra Social Personal Gráfico OSPG S1'),
('Obra Social Personal Gráfico OSPG S2'),
('Obra Social Provincia Plan único'),
('ObSBA Plan Único'),
('ODont Plan Medico Obligatorio'),
('Okey Group Plan Medico Obligatorio'),
('Okey Group Plan Medico Obligatorio'),
('Omint 3000'),
('Omint 3500'),
('Omint 4000'),
('Omint 4500'),
('Omint 6500'),
('Omint 8500'),
('Omint Cartilla 1'),
('Omint Cartilla 1000'),
('Omint Cartilla 1500'),
('Omint Cartilla 2'),
('Omint Cartilla 2000'),
('Omint Cartilla 2500'),
('Omint Cartilla 2600'),
('Omint Cartilla 2600N'),
('Omint Cartilla 2700'),
('Omint Cartilla 3'),
('Omint Cartilla 4'),
('Omint Cartilla 4021'),
('Omint CARTILLA 4500'),
('Omint Cartilla 600'),
('Omint Cartilla 6500'),
('Omint Cartilla 8500'),
('Omint Cartilla cuatro'),
('Omint Classic'),
('Omint Exento'),
('Omint Global'),
('Omint Gravado'),
('Omint Inicial AMBA'),
('Omint Interior'),
('Omint Linea efe'),
('Omint Linea f'),
('Omint Linea Genesis'),
('Omint Linea Interna'),
('Omint Linea O'),
('Omint Linea seleccion'),
('Omint Linea skill plus'),
('Omint Linea Y'),
('Omint Midoc'),
('Omint Omint'),
('Omint Omint genesis'),
('Omint Omint integral'),
('Omint Omint Linea O'),
('Omint Plan 1000'),
('Omint Plan 2000'),
('Omint Plan 3000'),
('Omint plus'),
('Omint Premium'),
('Omint Programa xxi'),
('Omint Seniors'),
('Omint Skill'),
('Opam Plan Único'),
('Opdea OP!'),
('Opdea PE'),
('Opdea Plan 00'),
('Opdea Plan 00N'),
('Opdea Plan 00S'),
('Opdea Plan 01'),
('Opdea Plan 02'),
('Opdea Plan 025'),
('Opdea Plan 02N'),
('Opdea Plan 03'),
('Opdea Plan 04'),
('Opdea Plan 05'),
('Opdea Plan 10'),
('Opdea Plan 12'),
('Opdea Plan 15'),
('Opdea Plan J6'),
('Opdea Plan xxi'),
('Optar Plan único'),
('Organizacion Medica SA Plan Medico Obligatorio'),
('Orsga Plan Único'),
('OS RECOLECCION BARRIDO Y LIMPIEZA Plan único'),
('OSADEF (Farmacias) Plan único'),
('OSAE Plan Medico Obligatorio'),
('OSALARA Plan Medico Obligatorio'),
('OSAM Salud No Mineros'),
('OSAM Salud Plan Único'),
('OSAMMVC (UOM Villa Constitución) Plan Medico Obligatorio'),
('OSAMOC Plan Único'),
('Osap Plan Único'),
('OSAPM (AAPM) Plan Entre Rios'),
('OSAPM (AAPM) Plan Único'),
('OSARPyH (alfajoreros, reposteros, pizzeros y heladeros) Plan Medico Obligatorio'),
('OSBA Plan único'),
('OSBARA Plan Medico Obligatorio'),
('OSBARA Plan único'),
('OSBLYCA Plan único'),
('OSCAP S.R.L Plan Único'),
('OSCBFM (Capitanes y Baqueanos Marina) Plan Médico Obligatorio'),
('osccptac (camioneros y choferes de cargas Cordoba) Plan Medico Obligatorio'),
('OSCEARA (Remiseros) Programa Medico Obligatorio'),
('OSCEP Capataces Estibadores Portuarios Plan Único'),
('OSCETSYL Plan Unico'),
('OSCHOCA Plan Único'),
('OSCICA - MICA Plan Único'),
('Osco Salud Azul'),
('Osco Salud Naranja'),
('Osco Salud Particular'),
('Osco Salud Unico'),
('OSCOEMA -Obreros Y Empleados Municipales- Plan único'),
('OSCONARA Atención primaria'),
('OSCTCP (ex UTA) Plan único'),
('OSDE 025'),
('OSDE 210'),
('OSDE 260'),
('OSDE 310'),
('OSDE 360'),
('OSDE 410'),
('OSDE 430'),
('OSDE 450'),
('OSDE 510'),
('OSDE 6030'),
('OSDE Flux'),
('OSDE Plan  030'),
('OSDE Plan 110'),
('OSDE Plan FLUX'),
('OSDEL (Locutores) Plan único'),
('OSDEL (Locutores) SC 100'),
('OSDEL (Locutores) SC 150'),
('OSDEL (Locutores) SC 250'),
('OSDEL (Locutores) SC 300'),
('OSDEL (Locutores) SC 50'),
('OSDEL (Locutores) SC 500'),
('OSDEL (Locutores) SC 550'),
('OSDEL (Locutores) SC 600'),
('Osdem (Musicos) Plan Medico Obligatorio'),
('Osdepym Personal'),
('Osdepym Pyme 1000'),
('Osdepym Pyme 2000'),
('Osdepym Pyme 3000'),
('Osdepym Pyme 4000'),
('Osdepym Pyme 800'),
('Osdepym Pyme STAFF'),
('Osdepym Visitar'),
('OSDIC DELTA'),
('OSDIC DELTA'),
('OSDIC KRONO'),
('OSDIC KRONO'),
('OSDIC QUANTUM'),
('OSDIC QUANTUM'),
('Osdipp 1'),
('Osdipp 1 Plus'),
('Osdipp 1 Plus Jerárquico'),
('Osdipp 100'),
('Osdipp 100 Plus'),
('Osdipp 150'),
('Osdipp 1D'),
('Osdipp 2'),
('Osdipp 200'),
('Osdipp 250'),
('Osdipp 250A'),
('Osdipp 2C'),
('Osdipp 2D'),
('Osdipp 3'),
('Osdipp 3 SL'),
('Osdipp 3 SQ'),
('Osdipp 300'),
('Osdipp 350'),
('Osdipp 3E'),
('Osdipp 4'),
('Osdipp 450'),
('Osdipp 450 F'),
('Osdipp Magnus'),
('Osdipp Osdipp'),
('Osdop Plan Único'),
('OSECAC Azul'),
('OSECAC Carhue'),
('OSECAC Complementaria'),
('OSECAC Funpresame'),
('OSECAC Monotributo'),
('OSECAC PMO'),
('OSECAC Río Negro'),
('OSEF Plan único'),
('OSEIV Plan único'),
('OSEMM Programa Medico Obligatorio'),
('OSEN (Electricistas Navales) Plan Médico Obligatorio'),
('OSEP Plan único'),
('Osepc (Prensa de Córdoba) Mas'),
('Osepc (Prensa de Córdoba) Prensa Mas'),
('Osepc (Prensa de Córdoba) Sol'),
('Osepjana Basico'),
('Osepjana COSTA'),
('Osepjana GBA'),
('Osepjana Senior'),
('OSER Plan Unico'),
('OSET Plan Único'),
('Osetra - Uetra (Empleados del Tabaco) Plan Médico Obligatorio'),
('Osetya Plan único'),
('OSF (Fedecamaras) Plan Medico Obligatorio'),
('OSFA fuerzas armadas Programa médico obligatorio'),
('OSFATLYF Plan único'),
('Osfatun Plan Básico'),
('Osfatun Plan Integral'),
('Osfatun Plan No Docente UN'),
('Osfatun Plan PMO'),
('Osfatun Plan Premium'),
('Osfe obra social ferroviaria Plan único'),
('OSFENTOS Plan único'),
('OSFFENTOS (Obras Sanitarias) S250'),
('OSFFENTOS (Obras Sanitarias) S500'),
('OSFFENTOS (Obras Sanitarias) SC 50'),
('OSFFENTOS (Obras Sanitarias) SC100'),
('OSFOT Plan único'),
('OSFYHC Plan único'),
('OSIAD Plan único'),
('OSIM Plan Médico Obligatorio'),
('OSITAC Plan único'),
('Osjera (Ospjera) Basico'),
('Osjera (Ospjera) Plan Basico Plus'),
('Osjera (Ospjera) Plan Único'),
('Osjera (Ospjera) PSO 600'),
('Osjera (Ospjera) PSO 700'),
('Osjera (Ospjera) PSO 800'),
('OSJPVFRA (jardineros, parq., viveros) Plan Medico Obligatorio'),
('Oslera 210'),
('Oslera 310'),
('Oslera Bordó'),
('Oslera Dorado'),
('Oslera Plan Basico Global'),
('Oslera Platino'),
('OSM (Obras Sanitarias Mendoza) Plan Medico Obligatorio'),
('OSMA Modelos Argentinos Plan Unico'),
('OSMATA Plan Único'),
('OSMATA PMI'),
('OSMATA PMO'),
('OSME Plan único'),
('OSMEBA SALUD Plan único'),
('Osmecon Almirante Brown'),
('Osmecon Esteban Echeverria'),
('Osmecon Ezeiza'),
('Osmecon La Matanza'),
('Osmecon Lomas de Zamora'),
('Osmecon Moron'),
('Osmecon Plan 4100'),
('Osmecon Plan 6000'),
('Osmecon Plan 7000'),
('Osmecon Plan 8000'),
('Osmecon Plan 9000'),
('Osmecon Plan D'),
('Osmecon Plan Dorado'),
('Osmecon Plan Global 4'),
('Osmecon Plan Global 5'),
('Osmecon Plan Integral'),
('Osmecon Plan Ultra'),
('Osmecon San Isidro'),
('Osmecon San Martin'),
('Osmecon Uno 4100'),
('Osmecon Uno 6000'),
('Osmecon Uno 7000'),
('Osmecon Uno 8000'),
('Osmecon Uno 9000'),
('Osmecon Vicente Lopez'),
('Osmecon salud Plan global 2'),
('Osmecon San Isidro Plan B 21'),
('Osmecon San Isidro Plan C - H - E - P - T - V - Z - L - K - B'),
('Osmecon San Isidro Plan Master'),
('Osmecon San Isidro Plan Médico'),
('Osmecon San Isidro Plan Mega'),
('Osmecon San Isidro Plan Mega 21'),
('Osmecon San Isidro Plan Omnium'),
('Osmecon San Isidro Plan Omnium 21'),
('Osmecon San Isidro Plan Senior'),
('Osmecon San Isidro PLAN TOTAL 12'),
('Osmecon San Isidro PLAN TOTAL 21'),
('Osmecon San Isidro PLAN TOTAL 21 &quot;A&quot;'),
('Osmecon San Isidro PLAN TOTAL 27'),
('Osmecon San Isidro Plan Ultra'),
('Osmecon San Isidro Plan Ultra Empresa'),
('Osmecon San Isidro Plan Vip 21'),
('Osmedica Plan Único'),
('OSMISS OSMISS 100'),
('OSMISS OSMISS 200'),
('OSMITA MIPLAN 10'),
('OSMITA MIPLAN 20'),
('OSMITA MIPLAN 30'),
('OSMITA PLAN FG24'),
('OSMITA PLAN MG5'),
('OSMITA PLAN MG6'),
('OSMITA PLAN MG7'),
('OSMITA PLAN MG8'),
('Osmmedt (Mandos Medios Telecomunicaciones) Plan Medico Obligatorio'),
('OSMTT Plan único'),
('OSOC (Operadores Cinematograficos) Plan Medico Obligatorio'),
('OSOCNA (Comisarios Navales) Plan Medico Obligatorio'),
('OSOETSYL Plan único'),
('Osoetsylra Plan Medico Asistencial'),
('OSOSS-Obra Social para Personal de Obras y Servicios Sanitarios Plan único'),
('OSPA-Obra Social del Personal Aeronautico PLAN BASICO'),
('OSPA-Obra Social del Personal Aeronautico PLAN PLATA'),
('OSPA-Obra Social del Personal Aeronautico Plan único'),
('OSPAC Plan único'),
('OSPACA Monotributistas'),
('OSPACA Plan único'),
('OSPACP Plan único'),
('OSPACTA Plan Único'),
('OSPADEP (Aeronavegantes Priv.) Plan Medico Asistencial'),
('OSPAGA Aguas Gaseosa Monotributistas y Adherentes Plan único'),
('OSPAGA Aguas Gaseosa Monotributistas y Adherentes Plan Unico'),
('OSPAGH (Gastronomicos) Plan Unico'),
('OSPAIL Plan único'),
('OSPAP (Obra Social Personal Perfumista) Plan Medico Obligatorio'),
('OSPAPARP Plan único'),
('OSPAT Plan único'),
('Ospatca Plan Único'),
('OSPAV Plan Medico Obligatorio'),
('OSPAVIAL Plan único'),
('OSPBB (Personal PBB Polisur) Plan Médico Obligatorio'),
('OSPBB (Personal PBB Polisur) Plan único'),
('OSPCRA Krono'),
('OSPCRA Plan SC-100'),
('OSPCRA Plan SC-150'),
('OSPCRA Plan SC-250'),
('OSPCRA Plan SC-50'),
('OSPCYD Plan Único'),
('OSPCYQ (Papel, Carton y Quimicos) Plan Unico'),
('OSPDEA - DIRECCION DE EMPRESAS DE ALIMENTOS Plan único'),
('OSPE 400'),
('OSPE 403'),
('OSPE 408'),
('OSPE 423'),
('OSPE 606'),
('OSPE 606'),
('OSPE 610'),
('OSPE 702'),
('OSPE A 301'),
('OSPE A 307'),
('OSPE A 323'),
('OSPE A-325'),
('OSPE A 401'),
('OSPE A-406'),
('OSPE A-411'),
('OSPE A-425'),
('OSPE A 600'),
('OSPE A-601'),
('OSPE A 602'),
('OSPE A-604'),
('OSPE A 700'),
('OSPE A-704'),
('OSPE A-706'),
('OSPE A608'),
('OSPE D-471'),
('OSPE D-752.'),
('OSPE D452'),
('OSPE D454'),
('OSPE D456'),
('OSPE Monotributo'),
('OSPE NASA'),
('OSPE NASSAT'),
('OSPE NOETINGER'),
('OSPE OPESSA'),
('OSPE OSPE SUR'),
('OSPE OSPE YPF'),
('OSPE OSPESSA'),
('OSPE Plan 602'),
('OSPE Plan PMO'),
('OSPE Plan Único'),
('OSPE Red Omip'),
('OSPE YPF-A'),
('OSPE YPF-B'),
('OSPEA (Personal Aerocomercial) Plan Médico Obligatorio'),
('Ospec (Personal del Correo) Plan Medico Obligatorio'),
('OSPECA -CAUCHO- Plan único'),
('OSPECHA Plan único'),
('OSPECON Plan Único'),
('OSPECON UOCRA'),
('OSPECOR Plan único'),
('OSPECT Plan único'),
('OSPEDICI -Cinematograficos- Plan único'),
('OSPEDYC Plan Único'),
('OSPEGA Plan único'),
('OSPEGAP Plan único'),
('Ospegype Plan Único'),
('OSPELSyM Plan azul'),
('OSPELSyM Plan platinum'),
('OSPELSyM Plan positiva'),
('OSPELSyM Primer plan'),
('OSPENA Personal Naval Plan único'),
('ospep Plan Único'),
('OSPEP (O.S. Personal del Espectáculo Público) Plan Medico Obligatorio'),
('OSPEP Obra Social del Personal de Panaderías Plan único'),
('OSPEPBA Plan Único'),
('OSPePri Plan Único'),
('OSPERHYRA Plan Médico Obligatorio'),
('OSPERSAAMS (Pers. Sancor) Plan Medico Obligatorio'),
('OSPERYHRA Plan Único'),
('osperyra Plan único'),
('ospes Plan Medico Asistencial'),
('OSPESA Plan Único'),
('OSPESCA Plan Medico Obligatorio'),
('OSPESCHA Plan Medico Obligatorio'),
('OSPESGA Plan único'),
('OSPESGyPE Plan Médico Obligatorio'),
('OSPeTax Plan único'),
('Ospetelco Azul'),
('Ospetelco Oro'),
('Ospetelco Plan E'),
('Ospetelco Plata'),
('OSPEVIC Plan único'),
('Ospfp Pintura Plan único'),
('Ospfp Pintura Plan Unico'),
('OSPIA Plan Único'),
('OSPIB Plan único'),
('OSPIC Benefic. M.C.A.'),
('OSPIC M.C.A'),
('OSPIC Monotributo'),
('OSPIC Plan Beneficiario'),
('OSPIC Plan Cine'),
('OSPIC Plan único'),
('OSPIC PMO'),
('OSPICA Plan único'),
('Ospical Plan único'),
('Ospida Programa Materno Infantil'),
('Ospida Programa Medico Obligatorio'),
('OSPIF Plan Bordo'),
('OSPIF Plan Platino'),
('OSPIF (Fideos) Plan Medico Obligatorio'),
('OSPIGPC - Industria Gráfica Córdoba Plan único'),
('Ospihmo Plan unico'),
('OSPIHMP Plan Único'),
('ospil Neuquén'),
('ospil Ospil'),
('ospil Plan córdoba'),
('ospil Plan Médico Obligatorio'),
('ospil Plan Médico Obligatorio'),
('ospil Plan Superador'),
('ospil Plan Villa Maria'),
('OSPILM (Ladrilleros a máquina) Plan Medico Obligatorio'),
('OSPIM Delta'),
('OSPIM Krono'),
('OSPIM Plan Único'),
('OSPIM Quantum'),
('Ospin Krono'),
('Ospin Ospin'),
('OSPIP Obra Social de Plastico Plan Unico'),
('OSPIQYP Quimicos y Petroquimicos Plan único'),
('OSPIS -Sanitarios- Plan único'),
('Ospit Plan Único'),
('OSPIV (Vestido) Plan Medico Obligatorio'),
('OSPIV (Vidrio) Plan Único'),
('Ospjn OSPJN Poder Judicial'),
('Ospjtap Plan Monotributo'),
('Ospjtap Plan Unico'),
('OSPL Plan Único'),
('OSPLA (Pilotos Lineas Aereas) Linea f'),
('OSPLA (Pilotos Lineas Aereas) Linea o'),
('OSPLA (Pilotos Lineas Aereas) Plan Medico Obligatorio'),
('OSPLAD Plan Medico Asistencial'),
('OSPM Obra Social del Personal de Maestranza Plan Médico Obligatorio'),
('OSPM Obra Social del Personal Marítimo Plan Único'),
('OSPM Obra Social Personal Mosaista Plan único'),
('OSPOCE Arrayán'),
('OSPOCE Ceibo'),
('OSPOCE Ospoce 01'),
('OSPOCE Roble'),
('OSPP -Personal de Publicidad- Plan único'),
('OSPPCyQ Ministerio de Salud'),
('OSPPCyQ Plan Único'),
('OSPPRA P.M.I.'),
('OSPPRA Plan Ambulatorio'),
('OSPPRA Plan Crónico'),
('OSPRA (PRENSA) Plan Unico'),
('OSPREM Plan único'),
('OSPREME (Automotriz) Plan Medico Obligatorio'),
('OSPRERA Monotributo'),
('OSPRERA Plan Único'),
('OSPRERA Rural'),
('OSPRO (Personal Prensa Rosario) Basico'),
('OSPRO (Personal Prensa Rosario) Clasico'),
('OSPRO (Personal Prensa Rosario) Superador'),
('OSPROTURA Plan Único'),
('OSPSA Plan único'),
('OSPSIP Todos los planes'),
('OSPSIP ASIS Plan único'),
('OSPT Plan único'),
('OSPTA Plan único'),
('OSPTV Plan único'),
('OSPUAYE (agua y energía) Plan unico'),
('Ospuncpba (Universidad) Plan Medico Obligatorio'),
('OSRGA Plan Único'),
('OSSACRA Clasico'),
('OSSACRA Profesional'),
('OSSACRA Programa Medico Obligatorio'),
('OSSACRA Social'),
('OSSACRA Total'),
('OSSANA Plan Médico Obligatorio'),
('OSSdeB -Serenos de Buques- Plan único'),
('OSSEG Adherentes'),
('OSSEG Especial'),
('OSSEG Gamma'),
('OSSEG Plan básico'),
('OSSEG Plan Integral'),
('OSSEG Plan Medico Obligatorio'),
('OSSEG Plan Salud'),
('OSSEG Plan Único'),
('OSSEIF (Ing. La Fronterita) Plan Medico Obligatorio'),
('OSSIMRA D2'),
('OSSIMRA Plan Médico Obligatorio'),
('OSSIMRA SC100'),
('OSSIMRA SC300'),
('Ossoelsac Plan único'),
('OSSURRBaC Plan único'),
('OSTAMMA Plan único'),
('OSTAXBA Plan unico'),
('OSTCARA Plan único'),
('OSTECF (Tecnicos de Futbol) Plan Medico Obligatorio'),
('OSTEE OSTEE'),
('Ostel Delta'),
('Ostel Gama'),
('Ostel Krono'),
('Ostel Plan Jubilados'),
('Ostel Plan STPlus (Azul)'),
('Ostel Plan T1000'),
('Ostel Plan T2500'),
('Ostel Plan T3000'),
('Ostel Plan Único'),
('Ostel Quantum'),
('OSTEP Plan Único'),
('OSTES (Estaciones de Servicio) Plan Medico Obligatorios'),
('OSTIG Plan Único'),
('OSTPCHPYARA (PASTELEROS Y CONFITEROS) Plan Unico'),
('Ostpcph Plan unico'),
('OSTPyGP Chubut Plan Médico Obligatorio'),
('OSTraC Plan Medico Asistencial'),
('OSTraC Plan Medico Obligatorio'),
('OSTV Trabajadores Viales Plan Classic'),
('OSTV Trabajadores Viales Plan Plus'),
('Ostvendra Plan Único'),
('OSTVLA (Tecnicos de Vuelo) Plan Medico Obligatorio'),
('OSUNER Plan único'),
('OSUNLaR Plan único'),
('OSUNR (Univ. Rosario) Plan Medico Obligatorio'),
('OSUNSa Plan Único'),
('OSUTHGRA Plan Único'),
('OSVARA (Vendedores Ambulantes) Plan Medico Obligatorio'),
('OSYC Plan único'),
('OSYPF Galeno Plata'),
('OSYPF Plan Oro'),
('OSYPF Plan Plata'),
('OSYPF Plan Único'),
('Pami O.P. (Orden de Prestación)'),
('Pami Pami Descuento Especial'),
('Pami Paritcular'),
('Pami Plan para Veteranos de Malvinas'),
('Pami Plan Unico'),
('Pami 2 Alergia'),
('Pami 2 AMBULATORIO NIVEL I'),
('Pami 2 ANATOMIA PATOLOGICA'),
('Pami 2 CARDIOLOGIA'),
('Pami 2 CIRUGIA DE CATARATAS'),
('Pami 2 CIRUGIA GENERAL AMBULATORIA'),
('Pami 2 CONSULTA ESP. NEUMONOLOGIA'),
('Pami 2 CONSULTA ESPECIALISTAS'),
('Pami 2 CONSULTA Y PRACT. OFT.'),
('Pami 2 CONSULTAS ESPECIALISTAS CARDIOLOGIA /ONCOLOGIA'),
('Pami 2 CONSULTAS Y PRACTICAS'),
('Pami 2 De cabecera'),
('Pami 2 DERMATOLOGIA'),
('Pami 2 DIABETOLOGIA'),
('Pami 2 ECO DIAGNOSTICO NIVEL I'),
('Pami 2 EN TRANSITO'),
('Pami 2 ENDOCRINOLOGIA'),
('Pami 2 FONOAUDIOLOGIA'),
('Pami 2 GASTROENTEROLOGIA'),
('Pami 2 GINECOLOGIA Y OBSTETRICIA'),
('Pami 2 HEMATOLOGIA'),
('Pami 2 INFECTOLOGIA'),
('Pami 2 NEFROLOGIA'),
('Pami 2 NEUMONOLOGIA'),
('Pami 2 NEUROLOGIA'),
('Pami 2 NEUROLOGIA ALTA COMPLEJIDAD'),
('Pami 2 NUTRICION'),
('Pami 2 OFT. COMPLEJAS'),
('Pami 2 OFTALMOLOGIA MODULO 38'),
('Pami 2 OFTALOMOLOGIA'),
('Pami 2 ONCOLOGIA - CONSULTAS'),
('Pami 2 OTORRINOLARINGOLOGIA'),
('Pami 2 PALIATIVOS Y DOLOR'),
('Pami 2 PAMI CONSULTA ESPECIALISTA'),
('Pami 2 PEDIATRIA'),
('Pami 2 PRACTICAS NEUROLOGICA'),
('Pami 2 PRACTICAS QUIRURGICAS'),
('Pami 2 TRAUMATOLOGIA'),
('Pami 2 Urologia'),
('PAMPA SALUD Plan Medico Obligatorio'),
('Panace Plan Aportes'),
('Panace Plan Prepago'),
('Papeleros Celeste'),
('Papeleros Naranja'),
('ParaRed Plan único'),
('Parque Salud Monotributo'),
('Parque Salud Relación de Dependencia'),
('Patrones de Cabotaje Plan básico'),
('Patrones de Cabotaje Plan especial'),
('Patrones de Cabotaje Plan superior'),
('Patrones de Cabotaje Plan Único'),
('PAULUCCI Plan Médico Obligatorio'),
('Paviotti Plan único'),
('PBS Plan Cardiológico'),
('PBS Inst. Cardiologia Plan Medico Obligatorio'),
('Pequeños y Medianos Plan único'),
('PERKINS OSTP Plan Médico Obligatorio'),
('Personal de Escribanía (OSPE) Plan Médico Obligatorio'),
('Personal de farmacia Plan único'),
('Pertenecer Salud Plan Único'),
('PETROLEROS Plan único'),
('PLAN DE SALUD DE LA DGI Plan único'),
('Plenit Plenit Exclusivo'),
('Plenit Plenit Live'),
('Plenit Plenit Premium'),
('PODER JUDICIAL DE LA NACION Plan único'),
('POLICIA FEDERAL Plan único'),
('Policia San Juan Plan con coseguro'),
('Policia San Juan Plan único'),
('Pre Medica S.A Plan Medico Obligatorio'),
('PREDECO Plan Medico Obligatorio'),
('PREME MEDICINA PRIVADA CORAL'),
('PREME MEDICINA PRIVADA MAR'),
('PREME MEDICINA PRIVADA OTROS'),
('PreMed Plan Medico Obligatorio'),
('Premedic 50'),
('Premedic 70'),
('Premedic 80'),
('Premedic Plan 0-50'),
('Premedic Plan 100'),
('Premedic Plan 200'),
('Premedic Plan 300'),
('Premedic Plan 400'),
('Premedic Plan 500'),
('Premedic Plan C100'),
('Premedic Plan Mayor Bronce'),
('Premedic Plan Mayor Platino'),
('Premedic Plan PMO'),
('Prensa Obra Social Plan Complementario'),
('Prensa Obra Social Plan Plus'),
('PREVENCION SALUD A con copago'),
('PREVENCION SALUD A1'),
('PREVENCION SALUD A1 Joven'),
('PREVENCION SALUD A2'),
('PREVENCION SALUD A2 Joven'),
('PREVENCION SALUD A3'),
('PREVENCION SALUD A3J'),
('PREVENCION SALUD A4'),
('PREVENCION SALUD A4J'),
('PREVENCION SALUD A5'),
('PREVENCION SALUD A5J'),
('PREVENCION SALUD A6'),
('PREVENCION SALUD A6 J'),
('PREVENCION SALUD OSPIM'),
('PREVENCION SALUD Plan Aliado'),
('PREVENCION SALUD Plan Básico'),
('PREVENCION SALUD Plan Joven'),
('PREVENCION SALUD Plan Materno Infantil'),
('PREVENCION SALUD Plan Mupepgam'),
('Primedic Salud B1'),
('Primedic Salud Superior'),
('Primedic Salud Superior Elite'),
('Primero - Medicina privada Plan 2100'),
('Primero - Medicina privada Plan 3100'),
('Primero - Medicina privada Plan 4000'),
('Primero - Medicina privada Plan 4100'),
('Primero - Medicina privada Plan 5000'),
('Primero - Medicina privada Plan 5100'),
('Primero - Medicina privada Plan 6000'),
('Primero - Medicina privada Plan 6100'),
('Primero - Medicina privada Plan Joven'),
('PRIVAMED Plan 330'),
('PRIVAMED Plan 550 y 550D'),
('PRIVAMED Plan 660'),
('PRIVAMED Plan 770 y 770D'),
('PRIVAMED Plan 880 y 880D'),
('PRIVAMED Plan NOVA 550'),
('PRIVAMED Plan NOVA 770'),
('PRIVAMED Plan NOVA 880'),
('Pro Salud PS 100'),
('Pro Salud PS 200'),
('Pro Salud PS 300'),
('Programa de Asistencia Sanitaria Social Plan Médico Obligatorio'),
('Programa de Salud Plan único'),
('Programas Medicos Plan único'),
('PROMAP Plan único'),
('Pronto Salud Plan Unico'),
('PROP MEDICA Plan único'),
('Protocolo Plan único'),
('Puerto Emergencia Plan P.E.01'),
('Qualitas Qualitas'),
('Qualitas Qualitas Azul'),
('Qualitas Qualitas Gris'),
('Qualitas Qualitas Premium'),
('Quince Plan Unico'),
('RED ARGENTINA DE SALUD RAS Plan único'),
('Red de Seguro Medico (SRL) Plan P.M.O.'),
('Red de Seguro Medico (SRL) Plan Premium'),
('Red de Seguro Medico (SRL) Plan Vip ORO'),
('RED MEDICA S.A. Plan Unico'),
('REDSOM SRL Plan único'),
('RELOJEROS, JOYEROS Y AFINES Plan Platino'),
('RELOJEROS, JOYEROS Y AFINES Plan Universal'),
('Ricardo Mora Servicios Sociales Plan único'),
('Rio Medica OSPM Plan único'),
('Rio Medica S.A. Plan único'),
('Roten Stein SRL Plan único'),
('RP Salud Plan Medico Obligatorio'),
('S.M.U.Vendedores de Diarios Plan unico'),
('S.P.F. (Servicio Penitenciario Federal) Plan Único'),
('S.P.S. (Prevención Social) Plan Único'),
('sadaic Plan único'),
('Saju Salud Plan 1100'),
('Saju Salud Plan 2100'),
('Saju Salud Plan 3100'),
('Salud del nuevo rosario Plan Unico'),
('SALUD INTEGRAL SALUD INTEGRAL GRAVADO( CONSALUD,PRESTADOR R.I.)'),
('SALUD INTEGRAL SALUD INTEGRAL NO GRAVADOS'),
('Salud Nacional Plan N inferior'),
('Salud Nacional Plan N superior'),
('Salud Patagonica Plan único'),
('Salud Plena 100'),
('Salud Plena 200'),
('Salud Plena 250'),
('Salud Plena 300'),
('Salud Total S.A. Plan S1'),
('Salud Total S.A. Plan S10'),
('Salud Total S.A. Plan S2'),
('Salud Total S.A. Plan S8'),
('Salud Total S.A. Plan S9'),
('Salus Plan Unico'),
('Salutias Salutias Esencial'),
('Salutias Salutias Plus'),
('Sami Salud Plan S1'),
('Sami Salud Plan S35'),
('San Andres Salud Plan Medico Obligatorio'),
('San Cristobal Seguros Plan Medico Obligatorio'),
('San Lucas Plan Unico'),
('SANAT. GARAY CAUCHO Plan único'),
('SANATORIO COBERTURA MEDICA Plan Único'),
('Sanatorio Plaza CSP'),
('Sanatorio San Jose Plan de Salud'),
('Sanatorio Santa Fe Plan Medico Obligatorio'),
('SANCOR 2500'),
('SANCOR 3500'),
('SANCOR 4065'),
('SANCOR 5000'),
('SANCOR 6000'),
('SANCOR 800'),
('SANCOR OSTEL'),
('SANCOR Plan 3000'),
('SANCOR Plan C'),
('SANCOR Plan único'),
('SANCOR S3000R'),
('SANCOR AMAS SALUD Plan único'),
('Sancor Salud 1000'),
('Sancor Salud 1000B'),
('Sancor Salud 1000D'),
('Sancor Salud 1000R'),
('Sancor Salud 1000S'),
('Sancor Salud 1500'),
('Sancor Salud 1500B'),
('Sancor Salud 1500D'),
('Sancor Salud 1500R'),
('Sancor Salud 1500S'),
('Sancor Salud 2000'),
('Sancor Salud 2000S'),
('Sancor Salud 2500'),
('Sancor Salud 3000'),
('Sancor Salud 3000B'),
('Sancor Salud 3000D'),
('Sancor Salud 3000E'),
('Sancor Salud 3000G'),
('Sancor Salud 3500'),
('Sancor Salud 3500D'),
('Sancor Salud 3500E'),
('Sancor Salud 4000'),
('Sancor Salud 4000E'),
('Sancor Salud 4000S'),
('Sancor Salud 4065'),
('Sancor Salud 4065E'),
('Sancor Salud 4065S'),
('Sancor Salud 4500'),
('Sancor Salud 4500S'),
('Sancor Salud 5000'),
('Sancor Salud 6000'),
('Sancor Salud 700V'),
('Sancor Salud Alta Complejidad'),
('Sancor Salud F700'),
('Sancor Salud F800'),
('Sancor Salud F800E'),
('Sancor Salud GEN 4000'),
('Sancor Salud GEN W 18-35'),
('Sancor Salud GEN XT 36-45'),
('Sancor Salud Gravados'),
('Sancor Salud No gravados'),
('Sancor Salud OSUTI BIENESTAR'),
('Sancor Salud OSUTI PLUS'),
('Sancor Salud PLAN C'),
('Sancor Salud Plan E'),
('Sancor Salud Plan S3000R'),
('Sancor Salud Plan S700A'),
('Sancor Salud Plan S800V'),
('Sancor Salud R3000'),
('Sancor Salud S 10'),
('Sancor Salud S 10C'),
('Sancor Salud S 10S'),
('Sancor Salud S 20'),
('Sancor Salud S 20C'),
('Sancor Salud S 20S'),
('Sancor Salud S3000'),
('Sancor Salud S3000R'),
('Sancor Salud S3500'),
('Sancor Salud S5000'),
('Sancor Salud S6000'),
('Sancor Salud S700'),
('Sancor Salud S700A'),
('Sancor Salud S70F'),
('Sancor Salud S800'),
('Sancor Salud S800V'),
('Sancor Salud SanCor 1000'),
('Sancor Salud SanCor 2000'),
('Sancor Salud SanCor 3000'),
('Sancor Salud SanCor 4000'),
('Sancor Salud SanCor 500'),
('Sancor Seguros Accidentes Personales'),
('Sancor Seguros Integro'),
('Sanidad Plan Médico Obligatorio'),
('SANIP Salud Plan único'),
('Sanos Salud Plan Azul'),
('Sanos Salud Plan Black'),
('Sanos Salud Plan Dorado'),
('Santa Clara Salud S.A. Plan Unico'),
('SANTE MEDICAL S'),
('SANTE MEDICAL V'),
('SAS Plan único'),
('SAT Plan único'),
('SCIS 1100'),
('SCIS 50'),
('SCIS Plan Ombú'),
('SCIS SC-100'),
('SCIS SC-150'),
('SCIS SC-250'),
('SCIS SC - 300'),
('SCIS SC-50'),
('SCIS SC-500'),
('SCIS SC-600'),
('SCIS Scis'),
('Seguridad Privada Plan único'),
('Seguro Escolar de la Provincia Plan Unico'),
('Seguro Publico de Salud Plan único'),
('SEMEGER PREPAGO Plan Unico'),
('SEMEGER PREPAGO Plan Unico'),
('SEMPRE Plan Unico'),
('Ser Salud Plan Confort'),
('Ser Salud Plan Group'),
('Ser Salud Plan Joven 18-30'),
('Ser Salud Plan Oro'),
('Ser Salud Plan Platinum'),
('Seres Salud 2.9'),
('Seres Salud 3.0'),
('SEROS Plan único'),
('Serve Salud A'),
('Serve Salud N 10'),
('Serve Salud N 20'),
('Serve Salud N-20 F'),
('Serve Salud N 30'),
('Serve Salud N 40'),
('Serve Salud N 40 SR'),
('Serve Salud N 50'),
('Serve Salud N 60'),
('Servesalud 20F'),
('Servesalud N 10'),
('Servesalud N 20'),
('Servesalud N 30'),
('Servesalud N 40'),
('Servesalud N 50'),
('Servesalud N60'),
('Servicios Sociales Bancarios Plan S-100'),
('Servicios Sociales Bancarios Plan S-200'),
('Servicios Sociales Bancarios Plan S-300'),
('SERVICIOS Y PRESTACIONES MEDICAS S.A Plan Único'),
('SIMECO Blue 1000'),
('SIMECO Blue 2000'),
('SIMECO Blue 9500'),
('SIMECO Gold 2100'),
('SIMECO Gold 3000'),
('SIMECO Integral'),
('SIMECO Platinum 5000'),
('SIMECO SA10'),
('SIMECO SA20'),
('SIMECO SA25'),
('SIMECO SA30'),
('SIMECO SA40'),
('SIMECO SC50'),
('SIMECO SC60'),
('SIMECO SC70'),
('SIMECO SC75'),
('SIMECO SC90'),
('SIMEPA Plan 2A'),
('SIMEPA Plan 2M'),
('SIMEPA Plan 3G'),
('SIMEPA Plan 3V'),
('SIMEPA Plan AO'),
('SIMEPA Plan OP'),
('SIMEPA Plan Plus'),
('Sin obra social Particular'),
('SIPAS Plan Médico Obligatorio'),
('SIPSSA A 100'),
('SIPSSA C 100'),
('SIPSSA C 200'),
('SIPSSA Plan Joven'),
('SIPSSA S 300'),
('SIPSSA S 310'),
('Sistema Médico Consejo Azul'),
('Sistema Médico Consejo Blue 1000'),
('SIVENDIA Plan Médico Obligatorio'),
('SM Salud Plan Medico Obligatorio'),
('SMAI Plan Único'),
('SMAUNaM Plan único'),
('Sociedad Cosmopolita Plan Unico'),
('Sociedad Española Plan Médico Obligatorio'),
('Sociedad Francesa Plan Médico Obligatorio'),
('Sociedad Italiana Plan Único'),
('SOESGYPE Plan Único'),
('somu Plan único'),
('SOP (Sistema Odontológico Privado) Plan Medico Obligatorio'),
('SOREMER Plan A'),
('SOREMER Plan C'),
('SOREMER Plan E'),
('SOREMER Plan Policial'),
('SOREMER Plan Vip'),
('SOS Salud Destacado'),
('SOS Salud Dorado'),
('SOS Salud Especial'),
('SOS Salud Estudiantil'),
('SOS Salud Primordial'),
('SOS Salud Privilegio'),
('SOS Salud Total'),
('SOSUNC Plan Único'),
('Sp Health Group Plan Medico Obligatorio'),
('SPF (Servicio Penitenciario) Plan Único'),
('SPM SALUD Plan Medico Obligatorio'),
('SRT Plan unico'),
('STADYCA Plan único'),
('Staff Medico Plan Amarillo'),
('Staff Medico Plan Fucsia'),
('Staff Medico Plan Turquesa'),
('Staff Medico Plan Verde'),
('Staff Medico S 100'),
('Staff Medico S 200'),
('Staff Medico S 250'),
('Staff Medico S 250J'),
('Staff Medico S 300'),
('Staff Medico S 350'),
('Staff Medico S 350J'),
('Staff Medico S 400'),
('Staff Medico S 450'),
('Su salud Plan Unico'),
('Subsidio de Salud Plan Unico'),
('SUMA Salud Plan único'),
('Sume Salud Sume100+S'),
('Sume Salud Sume200+S'),
('Sume Salud Sume300+S'),
('Sume Salud Sume400+S'),
('Sume Salud Sume500+S'),
('SUOEM Plan con coseguro'),
('SUOEM Plan único'),
('SUPERINTENDENCIA DE BIENESTAR DE LA POLICIA FEDERAL ARGENTINA Plan Único'),
('SUPERINTENDENCIA DE RIESGOS DEL TRABAJO Plan único'),
('SUTIAGA Plan único'),
('Swiss Medical Group 310000A'),
('Swiss Medical Group 334586F'),
('Swiss Medical Group 335735E'),
('Swiss Medical Group 412344E'),
('Swiss Medical Group 412845E'),
('Swiss Medical Group 41GL00B'),
('Swiss Medical Group 421545E'),
('Swiss Medical Group 43GB00F'),
('Swiss Medical Group Advance'),
('Swiss Medical Group AV1'),
('Swiss Medical Group BR63'),
('Swiss Medical Group CAN 1'),
('Swiss Medical Group CIL04'),
('Swiss Medical Group CL'),
('Swiss Medical Group CL10'),
('Swiss Medical Group CL107'),
('Swiss Medical Group DC1'),
('Swiss Medical Group DC3'),
('Swiss Medical Group DELTA'),
('Swiss Medical Group Docthos'),
('Swiss Medical Group E44'),
('Swiss Medical Group GAMA'),
('Swiss Medical Group GAMA7'),
('Swiss Medical Group Global'),
('Swiss Medical Group Global Simeco'),
('Swiss Medical Group HPGB'),
('Swiss Medical Group ICBC1'),
('Swiss Medical Group ISPLUS'),
('Swiss Medical Group IT 062'),
('Swiss Medical Group LVMH2'),
('Swiss Medical Group LVMH3'),
('Swiss Medical Group Medicien Azul'),
('Swiss Medical Group Medicien Gris'),
('Swiss Medical Group MS'),
('Swiss Medical Group MS3'),
('Swiss Medical Group Nubial Clasica'),
('Swiss Medical Group Nubial Clasica Plus'),
('Swiss Medical Group Nubial Quality'),
('Swiss Medical Group Nubial Quality Simeco'),
('Swiss Medical Group OL010'),
('Swiss Medical Group OPP'),
('Swiss Medical Group Optar'),
('Swiss Medical Group PL 310515c'),
('Swiss Medical Group Plan 04'),
('Swiss Medical Group Plan 4125'),
('Swiss Medical Group Plan Black'),
('Swiss Medical Group Plan Médico Obligatorio'),
('Swiss Medical Group Plan Parcial Ambulatorio'),
('Swiss Medical Group Plan Parcial Completo'),
('Swiss Medical Group Plan Parcial Internacion'),
('Swiss Medical Group Plan QST'),
('Swiss Medical Group Plus'),
('Swiss Medical Group PO02C'),
('Swiss Medical Group PO61'),
('Swiss Medical Group PO62C'),
('Swiss Medical Group PO63C'),
('Swiss Medical Group Premium'),
('Swiss Medical Group Premium Simeco'),
('Swiss Medical Group QC01P'),
('Swiss Medical Group Qualitas'),
('Swiss Medical Group Qualitas Gris'),
('Swiss Medical Group Qualitas Premium'),
('Swiss Medical Group Quality Simeco'),
('Swiss Medical Group SB02'),
('Swiss Medical Group SB03'),
('Swiss Medical Group SB04'),
('Swiss Medical Group SB61'),
('Swiss Medical Group SB62'),
('Swiss Medical Group SB63'),
('Swiss Medical Group Senior'),
('Swiss Medical Group Simeco'),
('Swiss Medical Group SM01'),
('Swiss Medical Group SM02'),
('Swiss Medical Group SM03'),
('Swiss Medical Group SM04'),
('Swiss Medical Group SM20'),
('Swiss Medical Group SM30'),
('Swiss Medical Group SM64'),
('Swiss Medical Group SMG'),
('Swiss Medical Group SMG 3200'),
('Swiss Medical Group SMG 40'),
('Swiss Medical Group SMG 50'),
('Swiss Medical Group SMG 60'),
('Swiss Medical Group SMG 70'),
('Swiss Medical Group SMG01'),
('Swiss Medical Group SMG02'),
('Swiss Medical Group SMG04'),
('Swiss Medical Group SMG10'),
('Swiss Medical Group SMG20'),
('Swiss Medical Group SMG30'),
('Swiss Medical Group SMG30C'),
('Swiss Medical Group Smg50'),
('Swiss Medical Group SO02'),
('Swiss Medical Group SO03'),
('Swiss Medical Group SO04'),
('Swiss Medical Group SO62'),
('Swiss Medical Group SO62'),
('Swiss Medical Group SO63'),
('Swiss Medical Group SO63'),
('Swiss Medical Group SO64'),
('Swiss Medical Group SO64'),
('Swiss Medical Group Swiss Medical'),
('Swiss Medical Group Swiss Medical Clio olivos'),
('Swiss Medical Group TE02'),
('Swiss Medical Group TEL2'),
('Swiss Medical Group Tel3'),
('Swiss Medical Group Tel4'),
('Swiss Medical Group TNI'),
('Swiss Medical Group V11 A'),
('Swiss Medical Group WM4'),
('Swiss Medical Group - Docthos Docthos Advance'),
('Swiss Medical Group - Docthos Docthos Basico'),
('Swiss Medical Group - Docthos Docthos Classic'),
('Swiss Medical Group - Docthos Docthos Family'),
('Swiss Medical Group - Docthos Docthos Global'),
('Swiss Medical Group - Docthos Docthos Grupo Salud'),
('Swiss Medical Group - Docthos Docthos Plus'),
('Swiss Medical Group - Docthos Docthos Premium'),
('Sygma Servicios Integrales Plan único'),
('Tadeo Czerweny Plan Medico Obligatorio'),
('Tombolini Plan Médico Obligatorio'),
('TRABAJADORES VENDEDORES DE DIARIOS REVISTAS Y AFINES Plan único'),
('Tunel Plan único'),
('Tv Salud 400'),
('Tv Salud Plan 100'),
('Tv Salud Plan 200'),
('Tv Salud Plan 300'),
('Tv Salud Plan OSPTV'),
('Tv Salud Plan SAT'),
('Tvsalud Plan unico'),
('Tzedaká Plan Único'),
('U24 Plan 404'),
('U24 Plan 505'),
('U24 Plan 606'),
('U24 Plan 707'),
('U24 Plan 808'),
('UAI Salud Azul 50'),
('UAI Salud Blanco'),
('UAI Salud Bronce'),
('UAI Salud Oro 1000'),
('UAI Salud Plan Plata 300'),
('UAI Salud Plan Plata 400'),
('UAI Salud Plata 500'),
('UDAP Plan con coseguro'),
('UDAP Plan con coseguro diferencial'),
('UDAP Plan único'),
('UNIMED HS 32'),
('UNIMED HS 45'),
('UNIMED HS 65'),
('UNIMED HS 85'),
('UNIMED HS 95'),
('UNIMED OSME PLAN 1'),
('UNIMED PMO'),
('UNIMED SPS 40'),
('UNIMED SPS 55'),
('UNIMED SPS 75'),
('UNIMED SPS 95'),
('Unimedica Colon'),
('Unimedica Rosario de Tala'),
('Unimedica Unimedica'),
('Union Personal 0001'),
('Union Personal 0002'),
('Union Personal 0004'),
('Union Personal 0005'),
('Union Personal 0006'),
('Union Personal 0008'),
('Union Personal 110'),
('Union Personal 210'),
('Union Personal 310'),
('Union Personal Dorado'),
('Union Personal Monotributista'),
('Union Personal Plan 0009'),
('Union Personal Plan Classic'),
('Union Personal Plan Familiar'),
('Union Personal PLAN MATERNO INFANTIL (PMI)'),
('Union Personal Plan P.M.O'),
('Union Personal Plan Verde'),
('Union Personal Platino'),
('Union Personal UP 10'),
('Unione e Benevolenza Plan A'),
('Univerdad Nacional La Plata Plan Medico Obligatorio'),
('Universal Assistance Plan Médico Obligatorio'),
('UNL Plan único'),
('UNLP CONVENIO DE REPROCIDAD Plan Único'),
('UNNE Plan Único'),
('UNO 1.1'),
('UNO 1.1 Amanus con coseguro'),
('UNO 1.2'),
('UNO 1.2 Amanus'),
('UNO 1.2 Fidelity'),
('UNO AZUL'),
('UNS (O.S Universidad Nac. del Sur) Plan Medico Obligatorio'),
('Unsa Plan Unico'),
('UOGC (Graficos Cordoba) Plan Unico'),
('Uom Union Obrera Metalurgica osuomra - Junin'),
('Uom Union Obrera Metalurgica osuomra - Pergamino'),
('Uom Union Obrera Metalurgica Plan único'),
('UPCN Plan Único'),
('UPSA Plan único'),
('UPSRA (O.S. PERSONAL DE SEGURIDAD COMERCIAL INDUSTRIAL E INVESTIGACIONES PRIVADA) Plan Único'),
('UTA Plan único'),
('UTEDYC Plan único'),
('UTEPLIM Plan A'),
('UTEPLIM Plan B'),
('UTEPLIM Plan Joven'),
('Valmed Plan Clásico'),
('Valmed Plan Gama'),
('Valmed Plan Global'),
('Valmed Plan Integral'),
('Valmed Plan Total'),
('Vareadores Plan único'),
('VESALIO SALUD Plan único'),
('VETERANOS DE GUERRA  INSSIJP - PAMI Plan único'),
('Via Sano Salud Plan 272 - Plan Monotributo'),
('Via Sano Salud Plan 353 PLUS - Recibo de Sueldo'),
('Via Sano Salud Plan 353 - Recibo de Sueldo'),
('Via Sano Salud Plan PMO 2'),
('Via Sano Salud Plan PMO'),
('Via Sano Salud Plan Provisorio'),
('Vialidad Nacional Plan Unico'),
('Visitar Adherentes'),
('Visitar Plan plus'),
('Visitar Plan Único'),
('Vitas Salud Mental'),
('Vittal Hogar Protegido'),
('Vittal Mix'),
('Vittal One'),
('Vive + Plan Unico'),
('WIlliam HOPE H24'),
('WIlliam HOPE H25'),
('WIlliam HOPE Hope Dorado'),
('WIlliam HOPE Hope H35'),
('WIlliam HOPE Hope L35'),
('WIlliam HOPE Hope Plateado'),
('WIlliam HOPE HR'),
('WIlliam HOPE HT'),
('WIlliam HOPE HU'),
('WIlliam HOPE HW'),
('WIlliam HOPE HX'),
('WIlliam HOPE HY'),
('WIlliam HOPE LR'),
('WIlliam HOPE LT'),
('WIlliam HOPE LU'),
('WIlliam HOPE LW'),
('WIlliam HOPE LX'),
('WIlliam HOPE LY'),
('WIlliam HOPE MS6'),
('WIlliam HOPE MS7'),
('WIlliam HOPE MS8'),
('WIlliam HOPE MS9'),
('WIlliam HOPE N35'),
('WIlliam HOPE NT'),
('WIlliam HOPE NU'),
('WIlliam HOPE NW'),
('WIlliam HOPE NY'),
('WIlliam HOPE O24'),
('WIlliam HOPE O25'),
('WIlliam HOPE O35'),
('WIlliam HOPE OS4'),
('WIlliam HOPE OS6'),
('WIlliam HOPE OS7'),
('WIlliam HOPE OS8'),
('WIlliam HOPE OS9'),
('WIlliam HOPE P35'),
('WIlliam HOPE Plan único'),
('WIlliam HOPE R'),
('WIlliam HOPE T'),
('WIlliam HOPE U'),
('WIlliam HOPE X'),
('WIlliam HOPE Y'),
('Word Salud Ospip'),
('Word Salud Plan único'),
('Worlybaires S.A Plan Medico Obligatorio');