SET NAMES utf8mb4;
TRUNCATE TABLE medicos_especialidades;
DELETE FROM especialidades;
DELETE FROM usuarios WHERE rol = 'medico';
INSERT INTO especialidades (id, nombre) VALUES (1, 'Alergia');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1000, 'local_1000', 'Maria Sol', 'Reyes (Mitre 124 – 4to Piso)', 'mariasol.reyes@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1000, 1);
INSERT INTO especialidades (id, nombre) VALUES (2, 'Cardiología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1001, 'local_1001', 'Sebastian', 'Bellia (Km1 / Pasaje Gutiérrez 980)', 'sebastian.bellia@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1001, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1002, 'local_1002', 'Jorge', 'Bocian (Km1 / Pasaje Gutiérrez 980)', 'jorge.bocian@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1002, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1003, 'local_1003', 'Juan Pablo', 'Bonifacio (Km1 / Pasaje Gutiérrez 980)', 'juanpablo.bonifacio@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1003, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1004, 'local_1004', 'Ana Lucia', 'Cimatti (Pasaje Gutiérrez 980)', 'analucia.cimatti@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1004, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1005, 'local_1005', 'Fernando', 'Nazzetta (Km1 / Pasaje Gutiérrez 980)', 'fernando.nazzetta@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1005, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1006, 'local_1006', 'Mariano', 'Trevisan (Km1 / Pasaje Gutiérrez 980)', 'mariano.trevisan@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1006, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1007, 'local_1007', 'Rodrigo', 'Albero (Mitre 124 – 4to Piso)', 'rodrigo.albero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1007, 2);
INSERT INTO especialidades (id, nombre) VALUES (3, 'Clínica médica');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1008, 'local_1008', 'Luis', 'Chiocconi (Mitre 124 – 3er Piso)', 'luis.chiocconi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1008, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1009, 'local_1009', 'Andres', 'Cisneros (Pasaje Gutiérrez 980)', 'andres.cisneros@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1009, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1010, 'local_1010', 'Maria Victoria', 'Cordi (Mitre 124 – 3er Piso)', 'mariavictoria.cordi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1010, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1011, 'local_1011', 'Rosina', 'Corrado (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'rosina.corrado@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1011, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1012, 'local_1012', 'María Cecilia', 'Ferrero (Mitre 124 – 3er piso)', 'maríacecilia.ferrero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1012, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1013, 'local_1013', 'Gustavo', 'Freier (Mitre 124 – 3er Piso)', 'gustavo.freier@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1013, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1014, 'local_1014', 'Marco', 'Hoffman (Mitre 124 – 3er Piso / 4to Piso)', 'marco.hoffman@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1014, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1015, 'local_1015', 'Moira', 'Laiolo (Frey 111)', 'moira.laiolo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1015, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1016, 'local_1016', 'Brenda', 'Lambrecht (Mitre 124 – 3er piso)', 'brenda.lambrecht@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1016, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1017, 'local_1017', 'Mara', 'Lopez Wortzman (Mitre 124 – 3er piso)', 'mara.lopezwortzman@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1017, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1018, 'local_1018', 'Magalí', 'Marcovich (Mitre 124 – 3er piso)', 'magalí.marcovich@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1018, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1019, 'local_1019', 'Virginia', 'Marquez (Mitre 124 – 3er Piso)', 'virginia.marquez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1019, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1020, 'local_1020', 'Paula', 'Montanaro (Mitre 124 – 4to Piso)', 'paula.montanaro@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1020, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1021, 'local_1021', 'Luciana', 'Orellano (Mitre 124 – 3er Piso)', 'luciana.orellano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1021, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1022, 'local_1022', 'Marcela', 'Plomer (Pasaje Gutiérrez 980)', 'marcela.plomer@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1022, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1023, 'local_1023', 'Rosario', 'Puente Olivera (Pasaje Gutiérrez 980)', 'rosario.puenteolivera@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1023, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1024, 'local_1024', 'Mariano', 'Signoretta (Mitre 124 – 4to Piso / Pasaje Gutiérrez 980)', 'mariano.signoretta@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1024, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1025, 'local_1025', 'Nadia', 'Szerman (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'nadia.szerman@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1025, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1026, 'local_1026', 'Guido', 'Torres', 'guido.torres@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1026, 3);
INSERT INTO especialidades (id, nombre) VALUES (4, 'Dermatología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1027, 'local_1027', 'Gisella', 'Marmonti (Frey 111)', 'gisella.marmonti@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1027, 4);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1028, 'local_1028', 'Juan', 'Serán (Frey 111)', 'juan.serán@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1028, 4);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1029, 'local_1029', 'Anabella', 'Giordano (Frey 111)', 'anabella.giordano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1029, 4);
INSERT INTO especialidades (id, nombre) VALUES (5, 'Diabetología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1030, 'local_1030', 'Arturo', 'López Rivera (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'arturo.lópezrivera@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1030, 5);
INSERT INTO especialidades (id, nombre) VALUES (6, 'Endocrinología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1031, 'local_1031', 'Romina', 'Caino (Pasaje Gutiérrez 980)', 'romina.caino@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1031, 6);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1032, 'local_1032', 'Jorge', 'López Giovanelli (Mitre 124 – 3er Piso)', 'jorge.lópezgiovanelli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1032, 6);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1033, 'local_1033', 'Maria Teresa', 'Nofal (Pasaje Gutiérrez 980)', 'mariateresa.nofal@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1033, 6);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1034, 'local_1034', 'Soledad', 'Rodríguez Prieto (Mitre 124 – 4to Piso)', 'soledad.rodríguezprieto@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1034, 6);
INSERT INTO especialidades (id, nombre) VALUES (7, 'Flebología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1035, 'local_1035', 'Julio', 'Cigorraga (Pasaje Gutiérrez 980)', 'julio.cigorraga@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1035, 7);
INSERT INTO especialidades (id, nombre) VALUES (8, 'Oncología');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1010, 8);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1036, 'local_1036', 'Pamela', 'Pérez (Mitre 124 – 3er Piso)', 'pamela.pérez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1036, 8);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1037, 'local_1037', 'Victoria', 'Sobrero (Mitre 124 – 4to Piso)', 'victoria.sobrero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1037, 8);
INSERT INTO especialidades (id, nombre) VALUES (9, 'Gastroenterología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1038, 'local_1038', 'Carlos', 'García Dans (Belgrano 100)', 'carlos.garcíadans@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1038, 9);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1039, 'local_1039', 'Iván', 'Mosca (Belgrano 100)', 'iván.mosca@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1039, 9);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1040, 'local_1040', 'German', 'Ortmann (Mitre 124 – 3er Piso / Belgrano 100)', 'german.ortmann@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1040, 9);
INSERT INTO especialidades (id, nombre) VALUES (10, 'Hematología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1041, 'local_1041', 'Andrés', 'Furque (Pasaje Gutiérrez 980 / Km1)', 'andrés.furque@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1041, 10);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1042, 'local_1042', 'Marcelo', 'Furque (Km1)', 'marcelo.furque@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1042, 10);
INSERT INTO especialidades (id, nombre) VALUES (11, 'Hepatología');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1021, 11);
INSERT INTO especialidades (id, nombre) VALUES (12, 'Neumonología infantil');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1043, 'local_1043', 'Florencia', 'Alessandrini (Mitre 124 – 4to Piso / Pasaje Gutiérrez 980)', 'florencia.alessandrini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1043, 12);
INSERT INTO especialidades (id, nombre) VALUES (13, 'Neurología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1044, 'local_1044', 'Maria Sol', 'Álvarez (Mitre 124 – 3er Piso)', 'mariasol.álvarez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1044, 13);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1045, 'local_1045', 'Jorge', 'Oliwa (Mitre 124 – 3er Piso)', 'jorge.oliwa@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1045, 13);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1046, 'local_1046', 'Fernanda', 'Villarroel (Pasaje Gutiérrez 980)', 'fernanda.villarroel@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1046, 13);
INSERT INTO especialidades (id, nombre) VALUES (14, 'Patología');
INSERT INTO especialidades (id, nombre) VALUES (15, 'Reumatología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1047, 'local_1047', 'Mario Andrés', 'Dr. Belini (Mitre 124 – 3er Piso)', 'marioandrés.dr.belini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1047, 15);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1048, 'local_1048', 'Carolina', 'Dra. Torre Walsh (Mitre 123 – 4to Piso)', 'carolina.dra.torrewalsh@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1048, 15);
INSERT INTO especialidades (id, nombre) VALUES (16, 'Terapia Intensiva');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1049, 'local_1049', 'Ariana', 'Ampuero (Km 1)', 'ariana.ampuero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1049, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1050, 'local_1050', 'Nicolas', 'Braida (Km 1)', 'nicolas.braida@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1050, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1051, 'local_1051', 'Carlos', 'Chilo (Km 1)', 'carlos.chilo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1051, 16);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1009, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1052, 'local_1052', 'Cynthia', 'Crende (Km 1)', 'cynthia.crende@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1052, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1053, 'local_1053', 'Lorena', 'Darrull (Km 1)', 'lorena.darrull@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1053, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1054, 'local_1054', 'Eduardo', 'Raemdonck (Km 1)', 'eduardo.raemdonck@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1054, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1055, 'local_1055', 'Fernanda', 'Rearte (Km 1)', 'fernanda.rearte@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1055, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1056, 'local_1056', 'Clara', 'Rodriguez (Km 1)', 'clara.rodriguez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1056, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1057, 'local_1057', 'Maite', 'Tamborindeguy (Km 1)', 'maite.tamborindeguy@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1057, 16);
INSERT INTO especialidades (id, nombre) VALUES (17, 'Infectología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1058, 'local_1058', 'Carlos', 'Barclay (Mitre 124 – 4to piso)', 'carlos.barclay@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1058, 17);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1059, 'local_1059', 'Federico', 'Spinelli (Pasaje Gutiérrez 980)', 'federico.spinelli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1059, 17);
INSERT INTO especialidades (id, nombre) VALUES (18, 'Nefrología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1060, 'local_1060', 'Soledad', 'Palazzo (Pasaje Gutiérrez 980)', 'soledad.palazzo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1060, 18);
INSERT INTO especialidades (id, nombre) VALUES (19, 'Deportología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1061, 'local_1061', 'Pablo', 'Cozzarin (Pasaje Gutiérrez 980)', 'pablo.cozzarin@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1061, 19);