SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE medicos_especialidades;
DELETE FROM especialidades;
DELETE FROM usuarios WHERE rol = 'medico';
INSERT INTO especialidades (id, nombre) VALUES (1, 'Alergia');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1000, 'local_1000', 'Maria Sol', 'Reyes (Mitre 124 – 4to Piso)', 'mariasol.reyes@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1000, 1);
INSERT INTO especialidades (id, nombre) VALUES (2, 'Cardiología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1001, 'local_1001', 'Sebastian', 'Bellia (Km1 / Pasaje Gutiérrez 980)', 'sebastian.bellia@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1001, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1002, 'local_1002', 'Jorge', 'Bocian (Km1 / Pasaje Gutiérrez 980)', 'jorge.bocian@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1002, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1003, 'local_1003', 'Juan Pablo', 'Bonifacio (Km1 / Pasaje Gutiérrez 980)', 'juanpablo.bonifacio@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1003, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1004, 'local_1004', 'Ana Lucia', 'Cimatti (Pasaje Gutiérrez 980)', 'analucia.cimatti@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1004, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1005, 'local_1005', 'Fernando', 'Nazzetta (Km1 / Pasaje Gutiérrez 980)', 'fernando.nazzetta@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1005, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1006, 'local_1006', 'Mariano', 'Trevisan (Km1 / Pasaje Gutiérrez 980)', 'mariano.trevisan@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1006, 2);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1007, 'local_1007', 'Rodrigo', 'Albero (Mitre 124 – 4to Piso)', 'rodrigo.albero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1007, 2);
INSERT INTO especialidades (id, nombre) VALUES (3, 'Clínica médica');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1008, 'local_1008', 'Luis', 'Chiocconi (Mitre 124 – 3er Piso)', 'luis.chiocconi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1008, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1009, 'local_1009', 'Andres', 'Cisneros (Pasaje Gutiérrez 980)', 'andres.cisneros@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1009, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1010, 'local_1010', 'Maria Victoria', 'Cordi (Mitre 124 – 3er Piso)', 'mariavictoria.cordi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1010, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1011, 'local_1011', 'Rosina', 'Corrado (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'rosina.corrado@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1011, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1012, 'local_1012', 'María Cecilia', 'Ferrero (Mitre 124 – 3er piso)', 'maríacecilia.ferrero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1012, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1013, 'local_1013', 'Gustavo', 'Freier (Mitre 124 – 3er Piso)', 'gustavo.freier@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1013, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1014, 'local_1014', 'Marco', 'Hoffman (Mitre 124 – 3er Piso / 4to Piso)', 'marco.hoffman@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1014, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1015, 'local_1015', 'Moira', 'Laiolo (Frey 111)', 'moira.laiolo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1015, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1016, 'local_1016', 'Brenda', 'Lambrecht (Mitre 124 – 3er piso)', 'brenda.lambrecht@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1016, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1017, 'local_1017', 'Mara', 'Lopez Wortzman (Mitre 124 – 3er piso)', 'mara.lopezwortzman@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1017, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1018, 'local_1018', 'Magalí', 'Marcovich (Mitre 124 – 3er piso)', 'magalí.marcovich@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1018, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1019, 'local_1019', 'Virginia', 'Marquez (Mitre 124 – 3er Piso)', 'virginia.marquez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1019, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1020, 'local_1020', 'Paula', 'Montanaro (Mitre 124 – 4to Piso)', 'paula.montanaro@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1020, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1021, 'local_1021', 'Luciana', 'Orellano (Mitre 124 – 3er Piso)', 'luciana.orellano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1021, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1022, 'local_1022', 'Marcela', 'Plomer (Pasaje Gutiérrez 980)', 'marcela.plomer@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1022, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1023, 'local_1023', 'Rosario', 'Puente Olivera (Pasaje Gutiérrez 980)', 'rosario.puenteolivera@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1023, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1024, 'local_1024', 'Mariano', 'Signoretta (Mitre 124 – 4to Piso / Pasaje Gutiérrez 980)', 'mariano.signoretta@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1024, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1025, 'local_1025', 'Nadia', 'Szerman (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'nadia.szerman@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1025, 3);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1026, 'local_1026', 'Guido', 'Torres', 'guido.torres@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1026, 3);
INSERT INTO especialidades (id, nombre) VALUES (4, 'Dermatología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1027, 'local_1027', 'Gisella', 'Marmonti (Frey 111)', 'gisella.marmonti@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1027, 4);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1028, 'local_1028', 'Juan', 'Serán (Frey 111)', 'juan.serán@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1028, 4);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1029, 'local_1029', 'Anabella', 'Giordano (Frey 111)', 'anabella.giordano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1029, 4);
INSERT INTO especialidades (id, nombre) VALUES (5, 'Diabetología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1030, 'local_1030', 'Arturo', 'López Rivera (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'arturo.lópezrivera@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1030, 5);
INSERT INTO especialidades (id, nombre) VALUES (6, 'Endocrinología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1031, 'local_1031', 'Romina', 'Caino (Pasaje Gutiérrez 980)', 'romina.caino@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1031, 6);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1032, 'local_1032', 'Jorge', 'López Giovanelli (Mitre 124 – 3er Piso)', 'jorge.lópezgiovanelli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1032, 6);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1033, 'local_1033', 'Maria Teresa', 'Nofal (Pasaje Gutiérrez 980)', 'mariateresa.nofal@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1033, 6);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1034, 'local_1034', 'Soledad', 'Rodríguez Prieto (Mitre 124 – 4to Piso)', 'soledad.rodríguezprieto@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1034, 6);
INSERT INTO especialidades (id, nombre) VALUES (7, 'Flebología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1035, 'local_1035', 'Julio', 'Cigorraga (Pasaje Gutiérrez 980)', 'julio.cigorraga@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1035, 7);
INSERT INTO especialidades (id, nombre) VALUES (8, 'Oncología');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1010, 8);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1036, 'local_1036', 'Pamela', 'Pérez (Mitre 124 – 3er Piso)', 'pamela.pérez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1036, 8);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1037, 'local_1037', 'Victoria', 'Sobrero (Mitre 124 – 4to Piso)', 'victoria.sobrero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1037, 8);
INSERT INTO especialidades (id, nombre) VALUES (9, 'Gastroenterología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1038, 'local_1038', 'Carlos', 'García Dans (Belgrano 100)', 'carlos.garcíadans@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1038, 9);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1039, 'local_1039', 'Iván', 'Mosca (Belgrano 100)', 'iván.mosca@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1039, 9);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1040, 'local_1040', 'German', 'Ortmann (Mitre 124 – 3er Piso / Belgrano 100)', 'german.ortmann@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1040, 9);
INSERT INTO especialidades (id, nombre) VALUES (10, 'Hematología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1041, 'local_1041', 'Andrés', 'Furque (Pasaje Gutiérrez 980 / Km1)', 'andrés.furque@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1041, 10);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1042, 'local_1042', 'Marcelo', 'Furque (Km1)', 'marcelo.furque@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1042, 10);
INSERT INTO especialidades (id, nombre) VALUES (11, 'Hepatología');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1021, 11);
INSERT INTO especialidades (id, nombre) VALUES (12, 'Neumonología infantil');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1043, 'local_1043', 'Florencia', 'Alessandrini (Mitre 124 – 4to Piso / Pasaje Gutiérrez 980)', 'florencia.alessandrini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1043, 12);
INSERT INTO especialidades (id, nombre) VALUES (13, 'Neurología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1044, 'local_1044', 'Maria Sol', 'Álvarez (Mitre 124 – 3er Piso)', 'mariasol.álvarez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1044, 13);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1045, 'local_1045', 'Jorge', 'Oliwa (Mitre 124 – 3er Piso)', 'jorge.oliwa@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1045, 13);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1046, 'local_1046', 'Fernanda', 'Villarroel (Pasaje Gutiérrez 980)', 'fernanda.villarroel@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1046, 13);
INSERT INTO especialidades (id, nombre) VALUES (14, 'Patología');
INSERT INTO especialidades (id, nombre) VALUES (15, 'Reumatología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1047, 'local_1047', 'Mario Andrés', 'Dr. Belini (Mitre 124 – 3er Piso)', 'marioandrés.dr.belini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1047, 15);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1048, 'local_1048', 'Carolina', 'Dra. Torre Walsh (Mitre 123 – 4to Piso)', 'carolina.dra.torrewalsh@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1048, 15);
INSERT INTO especialidades (id, nombre) VALUES (16, 'Terapia Intensiva');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1049, 'local_1049', 'Ariana', 'Ampuero (Km 1)', 'ariana.ampuero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1049, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1050, 'local_1050', 'Nicolas', 'Braida (Km 1)', 'nicolas.braida@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1050, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1051, 'local_1051', 'Carlos', 'Chilo (Km 1)', 'carlos.chilo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1051, 16);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1009, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1052, 'local_1052', 'Cynthia', 'Crende (Km 1)', 'cynthia.crende@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1052, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1053, 'local_1053', 'Lorena', 'Darrull (Km 1)', 'lorena.darrull@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1053, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1054, 'local_1054', 'Eduardo', 'Raemdonck (Km 1)', 'eduardo.raemdonck@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1054, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1055, 'local_1055', 'Fernanda', 'Rearte (Km 1)', 'fernanda.rearte@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1055, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1056, 'local_1056', 'Clara', 'Rodriguez (Km 1)', 'clara.rodriguez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1056, 16);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1057, 'local_1057', 'Maite', 'Tamborindeguy (Km 1)', 'maite.tamborindeguy@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1057, 16);
INSERT INTO especialidades (id, nombre) VALUES (17, 'Infectología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1058, 'local_1058', 'Carlos', 'Barclay (Mitre 124 – 4to piso)', 'carlos.barclay@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1058, 17);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1059, 'local_1059', 'Federico', 'Spinelli (Pasaje Gutiérrez 980)', 'federico.spinelli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1059, 17);
INSERT INTO especialidades (id, nombre) VALUES (18, 'Nefrología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1060, 'local_1060', 'Soledad', 'Palazzo (Pasaje Gutiérrez 980)', 'soledad.palazzo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1060, 18);
INSERT INTO especialidades (id, nombre) VALUES (19, 'Cirugía general');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1061, 'local_1061', 'Marcelo', 'Baratta (Pasaje Gutiérrez 980)', 'marcelo.baratta@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1061, 19);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1062, 'local_1062', 'Luis', 'Caride (Pasaje Gutiérrez 980)', 'luis.caride@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1062, 19);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1063, 'local_1063', 'Patricio', 'Gómez Constenla (Pasaje Gutiérrez 980)', 'patricio.gómezconstenla@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1063, 19);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1064, 'local_1064', 'Emiliano', 'Monti (Pasaje Gutiérrez 980)', 'emiliano.monti@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1064, 19);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1065, 'local_1065', 'Santiago', 'Olguin Joseau (Pasaje Gutiérrez 980)', 'santiago.olguinjoseau@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1065, 19);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1066, 'local_1066', 'Mariano', 'Sobrino (Mitre 124 – 3er Piso)', 'mariano.sobrino@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1066, 19);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1067, 'local_1067', 'Gonzalo', 'Varea (Pasaje Gutiérrez 980)', 'gonzalo.varea@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1067, 19);
INSERT INTO especialidades (id, nombre) VALUES (20, 'Cirugía pedriátrica');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1068, 'local_1068', 'Marcelo', 'Boer (Mitre 124 – 4to Piso)', 'marcelo.boer@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1068, 20);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1069, 'local_1069', 'Noiana', 'Etchepareborda (Mitre 124 – 4to Piso)', 'noiana.etchepareborda@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1069, 20);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1070, 'local_1070', 'Bianca', 'Grassano (Mitre 124 – 4to Piso)', 'bianca.grassano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1070, 20);
INSERT INTO especialidades (id, nombre) VALUES (21, 'Cirugía plástica');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1071, 'local_1071', 'Esteban', 'De Luca (Pasaje Gutiérrez 980)', 'esteban.deluca@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1071, 21);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1072, 'local_1072', 'Ruben', 'Niveiro (Pasaje Gutiérrez 980)', 'ruben.niveiro@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1072, 21);
INSERT INTO especialidades (id, nombre) VALUES (22, 'Cirugía vascular');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1073, 'local_1073', 'Miguel Angel', 'Ferrer Astrada (Pasaje Gutiérrez 980)', 'miguelangel.ferrerastrada@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1073, 22);
INSERT INTO especialidades (id, nombre) VALUES (23, 'Neurocirugía');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1074, 'local_1074', 'Raúl', 'Lucaccini (Pasaje Gutiérrez 980)', 'raúl.lucaccini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1074, 23);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1075, 'local_1075', 'Agustín', 'Maccio (Pasaje Gutiérrez 980)', 'agustín.maccio@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1075, 23);
INSERT INTO especialidades (id, nombre) VALUES (24, 'Oftalmología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1076, 'local_1076', 'Matías', 'Brizio (Frey 111)', 'matías.brizio@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1076, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1077, 'local_1077', 'Liliana', 'Diván (Frey 111)', 'liliana.diván@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1077, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1078, 'local_1078', 'Santiago', 'González Virgili (Frey 111)', 'santiago.gonzálezvirgili@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1078, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1079, 'local_1079', 'Rodrigo', 'Mantaras (Frey 111)', 'rodrigo.mantaras@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1079, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1080, 'local_1080', 'Ayelén', 'Moreno (Frey 111)', 'ayelén.moreno@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1080, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1081, 'local_1081', 'Jesica', 'Moyano (Frey 111)', 'jesica.moyano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1081, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1082, 'local_1082', 'Fabiana', 'Rueda (Frey 111)', 'fabiana.rueda@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1082, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1083, 'local_1083', 'Franco', 'Scaiano (Frey 111)', 'franco.scaiano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1083, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1084, 'local_1084', 'Romina', 'Soler (Frey 111)', 'romina.soler@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1084, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1085, 'local_1085', 'Nicolás', 'Suszko (Frey 111)', 'nicolás.suszko@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1085, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1086, 'local_1086', 'Natalia', 'Cortés (Frey 111)', 'natalia.cortés@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1086, 24);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1087, 'local_1087', 'Azul', 'Di Prospero (Frey 111)', 'azul.diprospero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1087, 24);
INSERT INTO especialidades (id, nombre) VALUES (25, 'Otorrinolaringología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1088, 'local_1088', 'Constanza', 'Carmona (Frey 111)', 'constanza.carmona@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1088, 25);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1089, 'local_1089', 'Patricia', 'Di Matteo (Frey 111)', 'patricia.dimatteo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1089, 25);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1090, 'local_1090', 'Pablo', 'Masoero (Frey 111)', 'pablo.masoero@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1090, 25);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1091, 'local_1091', 'Maria José', 'Quiróz (Frey 111)', 'mariajosé.quiróz@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1091, 25);
INSERT INTO especialidades (id, nombre) VALUES (26, 'Traumatología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1092, 'local_1092', 'Pablo', 'Albano (Pasaje Gutiérrez 980)', 'pablo.albano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1092, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1093, 'local_1093', 'Augusto', 'Cabrera Morrone (Pasaje Gutiérrez 980 / Km1)', 'augusto.cabreramorrone@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1093, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1094, 'local_1094', 'Diego', 'Di Santo (Pasaje Gutiérrez 980)', 'diego.disanto@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1094, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1095, 'local_1095', 'Mariano', 'Fernández (Pasaje Gutiérrez 980 / Km1)', 'mariano.fernández@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1095, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1096, 'local_1096', 'Daniel', 'Huerta Escandón (Pasaje Gutiérrez 980 / Km1)', 'daniel.huertaescandón@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1096, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1097, 'local_1097', 'German', 'Labencki (Pasaje Gutiérrez 980 / Km1)', 'german.labencki@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1097, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1098, 'local_1098', 'Gabriel', 'Ligios (Pasaje Gutiérrez 980 / Km1)', 'gabriel.ligios@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1098, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1099, 'local_1099', 'Martin', 'Luccón (Pasaje Gutiérrez 980 / Km1)', 'martin.luccón@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1099, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1100, 'local_1100', 'Fernando', 'Martínez (Pasaje Gutiérrez 980)', 'fernando.martínez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1100, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1101, 'local_1101', 'Adam', 'Paz Balka (Mitre 124 – 3er Piso)', 'adam.pazbalka@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1101, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1102, 'local_1102', 'Elías', 'Rodríguez (Pasaje Gutiérrez 980 / Km1)', 'elías.rodríguez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1102, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1103, 'local_1103', 'Marcelo', 'Viale (Pasaje Gutiérrez 980)', 'marcelo.viale@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1103, 26);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1104, 'local_1104', 'Martin', 'Vallone (Pasaje Gutiérrez 980)', 'martin.vallone@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1104, 26);
INSERT INTO especialidades (id, nombre) VALUES (27, 'Urología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1105, 'local_1105', 'Fernando', 'Colángelo (Pasaje Gutiérrez 980)', 'fernando.colángelo@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1105, 27);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1106, 'local_1106', 'Santiago', 'Rey (Pasaje Gutiérrez 980)', 'santiago.rey@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1106, 27);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1107, 'local_1107', 'Marcelo', 'Sandoval (Pasaje Gutiérrez 980)', 'marcelo.sandoval@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1107, 27);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1108, 'local_1108', 'Guillermo', 'Siffredi (Pasaje Gutiérrez 980)', 'guillermo.siffredi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1108, 27);
INSERT INTO especialidades (id, nombre) VALUES (28, 'Ginecología / obstetricia');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1109, 'local_1109', 'Miguel Ángel', 'Fernández (Pasaje Gutiérrez 980)', 'miguelángel.fernández@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1109, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1110, 'local_1110', 'Eduardo', 'García Platini (Pasaje Gutiérrez 980)', 'eduardo.garcíaplatini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1110, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1111, 'local_1111', 'Fabián', 'Gómez Giglio (Pasaje Gutiérrez 980)', 'fabián.gómezgiglio@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1111, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1112, 'local_1112', 'Cristina', 'González (Mitre 124 – 3er Piso)', 'cristina.gonzález@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1112, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1113, 'local_1113', 'Mercedes', 'Marqués Sanches Pérez (Pasaje Gutiérrez 980)', 'mercedes.marquéssanchespérez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1113, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1114, 'local_1114', 'Jimena', 'Martínez Almudevar (Pasaje Gutiérrez 980)', 'jimena.martínezalmudevar@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1114, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1115, 'local_1115', 'Gabriela', 'Mendía (Pasaje Gutiérrez 980)', 'gabriela.mendía@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1115, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1116, 'local_1116', 'Horacio', 'Paz (Mitre 124 – 3er Piso)', 'horacio.paz@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1116, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1117, 'local_1117', 'Norberto', 'Pierucci (Pasaje Gutiérrez 980)', 'norberto.pierucci@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1117, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1118, 'local_1118', 'Soledad', 'Ratto (Pasaje Gutiérrez 980)', 'soledad.ratto@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1118, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1119, 'local_1119', 'Bárbara', 'Riestra (Pasaje Gutiérrez 980)', 'bárbara.riestra@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1119, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1120, 'local_1120', 'Alicia', 'Rosas (Pasaje Gutiérrez 980)', 'alicia.rosas@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1120, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1121, 'local_1121', 'Mara', 'Valenti Arribillaga (Mitre 124 – 3er Piso / Pasaje Gutiérrez 980)', 'mara.valentiarribillaga@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1121, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1122, 'local_1122', 'Gustavo', 'Vilaseco (Mitre 124 – 3er Piso)', 'gustavo.vilaseco@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1122, 28);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1123, 'local_1123', 'Betiana', 'Butus (Pasaje Gutiérrez 980)', 'betiana.butus@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1123, 28);
INSERT INTO especialidades (id, nombre) VALUES (29, 'Mastología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1124, 'local_1124', 'Maria Florencia', 'Costantino (Pasaje Gutiérrez 980)', 'mariaflorencia.costantino@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1124, 29);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1125, 'local_1125', 'Carolina', 'Pasquali (Pasaje Gutiérrez 980)', 'carolina.pasquali@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1125, 29);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1116, 29);
INSERT INTO especialidades (id, nombre) VALUES (30, 'Neonatología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1126, 'local_1126', 'Oscar', 'Angarita (Km 1)', 'oscar.angarita@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1126, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1127, 'local_1127', 'Carla', 'Angelelli (Km 1)', 'carla.angelelli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1127, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1128, 'local_1128', 'Ana', 'Ardenghi (Km 1)', 'ana.ardenghi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1128, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1129, 'local_1129', 'Sebastian', 'Ilera (Km 1)', 'sebastian.ilera@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1129, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1130, 'local_1130', 'Laura', 'Lizzasu (Km 1)', 'laura.lizzasu@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1130, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1131, 'local_1131', 'Julieta', 'Lisotti (Km 1)', 'julieta.lisotti@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1131, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1132, 'local_1132', 'Luciana', 'Morresi (Km 1)', 'luciana.morresi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1132, 30);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1133, 'local_1133', 'Mariela', 'Vilte (Km 1)', 'mariela.vilte@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1133, 30);
INSERT INTO especialidades (id, nombre) VALUES (31, 'Esp. pediátricas');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1134, 'local_1134', 'Mariana', 'Berardone (Mitre 124 – 4to Piso)', 'mariana.berardone@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1134, 31);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1135, 'local_1135', 'Gustavo', 'Congin (Mitre 124 – 4to Piso / Frey 111)', 'gustavo.congin@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1135, 31);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1136, 'local_1136', 'Maria Clara', 'Deandreis (Mitre 124 – 4to Piso)', 'mariaclara.deandreis@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1136, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1129, 31);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1137, 'local_1137', 'Nadia', 'Paladino (Mitre 124 – 4to Piso)', 'nadia.paladino@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1137, 31);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1138, 'local_1138', 'Maximiliano', 'Pellegrini (Mitre 124 – 4to Piso)', 'maximiliano.pellegrini@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1138, 31);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1139, 'local_1139', 'Sabrina', 'Stranges (Mitre 124 – 4to Piso)', 'sabrina.stranges@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1139, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1007, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1068, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1069, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1070, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1029, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1034, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1043, 31);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1140, 'local_1140', 'Ana Lais', 'De Napoli (Mitre 124 – 4to piso)', 'analais.denapoli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1140, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1086, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1087, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1080, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1037, 31);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1048, 31);
INSERT INTO especialidades (id, nombre) VALUES (32, 'Fonoaudiología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1141, 'local_1141', 'Stella', 'Matteozzi (Frey 111)', 'stella.matteozzi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1141, 32);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1142, 'local_1142', 'María Marcela', 'Orrico (Frey 111)', 'maríamarcela.orrico@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1142, 32);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1143, 'local_1143', 'Brigitte', 'Schwarz (Frey 111)', 'brigitte.schwarz@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1143, 32);
INSERT INTO especialidades (id, nombre) VALUES (33, 'Nutrición');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1144, 'local_1144', 'Stella', 'Rovera (Pasaje Gutiérrez 980)', 'stella.rovera@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1144, 33);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1145, 'local_1145', 'Giovanna', 'Tonello (Mitre 124 – 3er Piso)', 'giovanna.tonello@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1145, 33);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1146, 'local_1146', 'Ana Lair', 'De Napoli (Mitre 124 – 4to piso)', 'analair.denapoli@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1146, 33);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1147, 'local_1147', 'Alejandra', 'Rossi (Frey 111)', 'alejandra.rossi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1147, 33);
INSERT INTO especialidades (id, nombre) VALUES (34, 'Odontología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1148, 'local_1148', 'Julián', 'Melzi (Mitre 124 – 4to Piso)', 'julián.melzi@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1148, 34);
INSERT INTO especialidades (id, nombre) VALUES (35, 'Psicología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1149, 'local_1149', 'Marcela', 'Celano (Mitre 124 – 4to Piso)', 'marcela.celano@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1149, 35);
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1150, 'local_1150', 'Tomas Agustin', 'De Santis (Mitre 124 – 4to piso)', 'tomasagustin.desantis@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1150, 35);
INSERT INTO especialidades (id, nombre) VALUES (36, 'Psiquiatría');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1151, 'local_1151', 'Agustina', 'Gómez (Mitre 124 4to Piso)', 'agustina.gómez@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1151, 36);
INSERT INTO especialidades (id, nombre) VALUES (37, 'Deportología');
INSERT INTO usuarios (id, firebase_uid, nombre, apellido, email, rol, contrasena) VALUES (1152, 'local_1152', 'Pablo', 'Cozzarin (Pasaje Gutiérrez 980)', 'pablo.cozzarin@sancarlos.com', 'medico', '$2y$10$abcdefghijklmnopqrstuv');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1152, 37);