SET NAMES utf8mb4;
TRUNCATE TABLE medicos_especialidades;
DELETE FROM especialidades;
DELETE FROM usuarios WHERE rol = 'medico';
INSERT INTO especialidades (id, nombre) VALUES (1, 'Alergia');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1000, 'Maria Sol', 'Reyes', 'mariasol.reyes@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1000, 1);
INSERT INTO especialidades (id, nombre) VALUES (2, 'Cardiología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1001, 'Sebastian', 'Bellia', 'sebastian.bellia@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1001, 2);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1002, 'Jorge', 'Bocian', 'jorge.bocian@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1002, 2);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1003, 'Juan Pablo', 'Bonifacio', 'juanpablo.bonifacio@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1003, 2);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1004, 'Ana Lucia', 'Cimatti', 'analucia.cimatti@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1004, 2);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1005, 'Fernando', 'Nazzetta', 'fernando.nazzetta@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1005, 2);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1006, 'Mariano', 'Trevisan', 'mariano.trevisan@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1006, 2);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1007, 'Rodrigo', 'Albero', 'rodrigo.albero@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1007, 2);
INSERT INTO especialidades (id, nombre) VALUES (3, 'Clínica médica');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1008, 'Luis', 'Chiocconi', 'luis.chiocconi@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1008, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1009, 'Andres', 'Cisneros', 'andres.cisneros@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1009, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1010, 'Maria Victoria', 'Cordi', 'mariavictoria.cordi@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1010, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1011, 'Rosina', 'Corrado', 'rosina.corrado@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1011, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1012, 'María Cecilia', 'Ferrero', 'mariacecilia.ferrero@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1012, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1013, 'Gustavo', 'Freier', 'gustavo.freier@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1013, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1014, 'Marco', 'Hoffman', 'marco.hoffman@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1014, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1015, 'Moira', 'Laiolo', 'moira.laiolo@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1015, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1016, 'Brenda', 'Lambrecht', 'brenda.lambrecht@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1016, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1017, 'Mara', 'Lopez Wortzman', 'mara.lopezwortzman@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1017, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1018, 'Magalí', 'Marcovich', 'magali.marcovich@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1018, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1019, 'Virginia', 'Marquez', 'virginia.marquez@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1019, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1020, 'Paula', 'Montanaro', 'paula.montanaro@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1020, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1021, 'Luciana', 'Orellano', 'luciana.orellano@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1021, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1022, 'Marcela', 'Plomer', 'marcela.plomer@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1022, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1023, 'Rosario', 'Puente Olivera', 'rosario.puenteolivera@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1023, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1024, 'Mariano', 'Signoretta', 'mariano.signoretta@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1024, 3);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1025, 'Nadia', 'Szerman', 'nadia.szerman@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1025, 3);
INSERT INTO especialidades (id, nombre) VALUES (4, 'Dermatología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1026, 'Gisella', 'Marmonti', 'gisella.marmonti@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1026, 4);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1027, 'Juan', 'Serán', 'juan.seran@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1027, 4);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1028, 'Anabella', 'Giordano', 'anabella.giordano@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1028, 4);
INSERT INTO especialidades (id, nombre) VALUES (5, 'Diabetología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1029, 'Arturo', 'López Rivera', 'arturo.lopezrivera@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1029, 5);
INSERT INTO especialidades (id, nombre) VALUES (6, 'Endocrinología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1030, 'Romina', 'Caino', 'romina.caino@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1030, 6);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1031, 'Jorge', 'López Giovanelli', 'jorge.lopezgiovanelli@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1031, 6);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1032, 'Maria Teresa', 'Nofal', 'mariateresa.nofal@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1032, 6);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1033, 'Soledad', 'Rodríguez Prieto', 'soledad.rodriguezprieto@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1033, 6);
INSERT INTO especialidades (id, nombre) VALUES (7, 'Flebología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1034, 'Julio', 'Cigorraga', 'julio.cigorraga@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1034, 7);
INSERT INTO especialidades (id, nombre) VALUES (8, 'Oncología');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1010, 8);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1035, 'Pamela', 'Pérez', 'pamela.perez@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1035, 8);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1036, 'Victoria', 'Sobrero', 'victoria.sobrero@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1036, 8);
INSERT INTO especialidades (id, nombre) VALUES (9, 'Gastroenterología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1037, 'Carlos', 'García Dans', 'carlos.garciadans@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1037, 9);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1038, 'Iván', 'Mosca', 'ivan.mosca@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1038, 9);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1039, 'German', 'Ortmann', 'german.ortmann@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1039, 9);
INSERT INTO especialidades (id, nombre) VALUES (10, 'Hematología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1040, 'Andrés', 'Furque', 'andres.furque@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1040, 10);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1041, 'Marcelo', 'Furque', 'marcelo.furque@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1041, 10);
INSERT INTO especialidades (id, nombre) VALUES (11, 'Hepatología');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1021, 11);
INSERT INTO especialidades (id, nombre) VALUES (12, 'Neumonología infantil');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1042, 'Florencia', 'Alessandrini', 'florencia.alessandrini@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1042, 12);
INSERT INTO especialidades (id, nombre) VALUES (13, 'Neurología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1043, 'Maria Sol', 'Álvarez', 'mariasol.alvarez@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1043, 13);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1044, 'Jorge', 'Oliwa', 'jorge.oliwa@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1044, 13);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1045, 'Fernanda', 'Villarroel', 'fernanda.villarroel@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1045, 13);
INSERT INTO especialidades (id, nombre) VALUES (14, 'Patología');
INSERT INTO especialidades (id, nombre) VALUES (15, 'Reumatología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1046, 'Mario Andrés', 'Dr. Belini', 'marioandres.dr.belini@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1046, 15);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1047, 'Carolina', 'Dra. Torre Walsh', 'carolina.dra.torrewalsh@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1047, 15);
INSERT INTO especialidades (id, nombre) VALUES (16, 'Terapia Intensiva');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1048, 'Ariana', 'Ampuero', 'ariana.ampuero@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1048, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1049, 'Nicolas', 'Braida', 'nicolas.braida@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1049, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1050, 'Carlos', 'Chilo', 'carlos.chilo@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1050, 16);
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1009, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1051, 'Cynthia', 'Crende', 'cynthia.crende@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1051, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1052, 'Lorena', 'Darrull', 'lorena.darrull@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1052, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1053, 'Eduardo', 'Raemdonck', 'eduardo.raemdonck@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1053, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1054, 'Fernanda', 'Rearte', 'fernanda.rearte@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1054, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1055, 'Clara', 'Rodriguez', 'clara.rodriguez@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1055, 16);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1056, 'Maite', 'Tamborindeguy', 'maite.tamborindeguy@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1056, 16);
INSERT INTO especialidades (id, nombre) VALUES (17, 'Infectología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1057, 'Carlos', 'Barclay', 'carlos.barclay@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1057, 17);
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1058, 'Federico', 'Spinelli', 'federico.spinelli@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1058, 17);
INSERT INTO especialidades (id, nombre) VALUES (18, 'Nefrología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1059, 'Soledad', 'Palazzo', 'soledad.palazzo@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1059, 18);
INSERT INTO especialidades (id, nombre) VALUES (19, 'Deportología');
INSERT INTO usuarios (id, nombre, apellido, email, rol, contrasena) VALUES (1060, 'Pablo', 'Cozzarin', 'pablo.cozzarin@sancarlos.com', 'medico', '123456');
INSERT INTO medicos_especialidades (usuario_id, especialidad_id) VALUES (1060, 19);